// lib/opps/geo.ts

export const COUNTRIES = [
  { code: 'IT', label: 'Italia' },
  { code: 'ES', label: 'Spagna' },
  { code: 'FR', label: 'Francia' },
  { code: 'DE', label: 'Germania' },
  { code: 'GB', label: 'Regno Unito' },
  { code: 'PT', label: 'Portogallo' },
  { code: 'NL', label: 'Paesi Bassi' },
  { code: 'BE', label: 'Belgio' },
  { code: 'CH', label: 'Svizzera' },
  { code: 'US', label: 'USA' },
  { code: 'BR', label: 'Brasile' },
  { code: 'AR', label: 'Argentina' },
  { code: 'OTHER', label: 'Altro…' },
];

// Regioni (testi esattamente come forniti)
export const ITALY_REGIONS = [
  'Abruzzo',
  'Basilicata',
  'Calabria',
  'Campania',
  'Emilia-Romagna',
  'Friuli-Venezia Giulia',
  'Lazio',
  'Liguria',
  'Lombardia',
  'Marche',
  'Molise',
  'Piemonte',
  'Puglia',
  'Sardegna',
  'Sicilia',
  'Toscana',
  'Trentino-Alto Adige',
  'Umbria',
  "Valle d'Aosta",
  'Veneto',
] as const;

// Province per regione (come da tuo elenco)
export const PROVINCES_BY_REGION: Record<string, string[]> = {
  Abruzzo: ["L'Aquila", 'Chieti', 'Pescara', 'Teramo'],
  Basilicata: ['Matera', 'Potenza'],
  Calabria: ['Catanzaro', 'Cosenza', 'Crotone', 'Reggio Calabria', 'Vibo Valentia'],
  Campania: ['Avellino', 'Benevento', 'Caserta', 'Napoli', 'Salerno'],
  'Emilia-Romagna': [
    'Bologna',
    'Ferrara',
    'Forlì-Cesena',
    'Modena',
    'Parma',
    'Piacenza',
    'Ravenna',
    'Reggio Emilia',
    'Rimini',
  ],
  'Friuli-Venezia Giulia': ['Gorizia', 'Pordenone', 'Trieste', 'Udine'],
  Lazio: ['Frosinone', 'Latina', 'Rieti', 'Roma', 'Viterbo'],
  Liguria: ['Genova', 'Imperia', 'La Spezia', 'Savona'],
  Lombardia: [
    'Bergamo',
    'Brescia',
    'Como',
    'Cremona',
    'Lecco',
    'Lodi',
    'Mantova',
    'Milano',
    'Monza e Brianza',
    'Pavia',
    'Sondrio',
    'Varese',
  ],
  Marche: ['Ancona', 'Ascoli Piceno', 'Fermo', 'Macerata', 'Pesaro e Urbino'],
  Molise: ['Campobasso', 'Isernia'],
  Piemonte: [
    'Alessandria',
    'Asti',
    'Biella',
    'Cuneo',
    'Novara',
    'Torino',
    'Verbano-Cusio-Ossola',
    'Vercelli',
  ],
  Puglia: ['Bari', 'Barletta-Andria-Trani', 'Brindisi', 'Foggia', 'Lecce', 'Taranto'],
  Sardegna: ['Cagliari', 'Sassari', 'Oristano', 'Nuoro', 'Sud Sardegna'],
  Sicilia: [
    'Agrigento',
    'Caltanissetta',
    'Catania',
    'Enna',
    'Messina',
    'Palermo',
    'Ragusa',
    'Siracusa',
    'Trapani',
  ],
  Toscana: [
    'Arezzo',
    'Firenze',
    'Grosseto',
    'Livorno',
    'Lucca',
    'Massa-Carrara',
    'Pisa',
    'Pistoia',
    'Prato',
    'Siena',
  ],
  'Trentino-Alto Adige': ['Bolzano', 'Trento'],
  Umbria: ['Perugia', 'Terni'],
  "Valle d'Aosta": ['Aosta'],
  Veneto: ['Belluno', 'Padova', 'Rovigo', 'Treviso', 'Venezia', 'Verona', 'Vicenza'],
};

// Comuni noti per le province (Siracusa già c'era; ora aggiungiamo Roma)
export const CITIES_BY_PROVINCE: Record<string, string[]> = {
  Siracusa: [
    'Augusta',
    'Avola',
    'Buccheri',
    'Buscemi',
    'Canicattini Bagni',
    'Carlentini',
    'Cassaro',
    'Ferla',
    'Floridia',
    'Francofonte',
    'Lentini',
    'Melilli',
    'Noto',
    'Pachino',
    'Palazzolo Acreide',
    'Portopalo di Capo Passero',
    'Priolo Gargallo',
    'Rosolini',
    'Siracusa',
    'Solarino',
    'Sortino',
  ],

  // === Provincia di Roma ===
  Roma: [
    'Affile',
    'Agosta',
    'Albano Laziale',
    'Allumiere',
    'Anguillara Sabazia',
    'Anticoli Corrado',
    'Anzio',
    'Arcinazzo Romano',
    'Ardea',
    'Ariccia',
    'Arsoli',
    'Artena',
    'Bellegra',
    'Bracciano',
    'Camerata Nuova',
    'Campagnano di Roma',
    'Canale Monterano',
    'Canterano',
    'Capena',
    'Capranica Prenestina',
    'Carpineto Romano',
    'Casape',
    'Castel Gandolfo',
    'Castel Madama',
    'Castel San Pietro Romano',
    'Castelnuovo di Porto',
    'Cave',
    'Cerreto Laziale',
    'Cervara di Roma',
    'Cerveteri',
    'Ciampino',
    'Ciciliano',
    'Cineto Romano',
    'Civitavecchia',
    'Civitella San Paolo',
    'Colleferro',
    'Colonna',
    'Fiano Romano',
    'Filacciano',
    'Fiumicino',
    // Nota: "Fonte Nuova e Mentana" viene normalizzato in "Fonte Nuova" (Mentana è già sotto)
    'Fonte Nuova',
    'Formello',
    'Frascati',
    'Gallicano nel Lazio',
    'Gavignano',
    'Genazzano',
    'Genzano di Roma',
    'Gerano',
    'Gorga',
    'Grottaferrata',
    'Guidonia Montecelio',
    'Jenne',
    'Labico',
    'Ladispoli',
    'Lanuvio',
    'Lariano',
    'Licenza',
    'Magliano Romano',
    'Mandela',
    'Manziana',
    'Marano Equo',
    'Marcellina',
    'Marino',
    'Mazzano Romano',
    'Mentana',
    'Montecompatri',
    'Monteflavio',
    'Montelanico',
    'Montelibretti',
    'Monte Porzio Catone',
    'Monterotondo',
    'Montorio Romano',
    'Moricone',
    'Morlupo',
    'Nazzano',
    'Nemi',
    'Nerola',
    'Nettuno',
    'Olevano Romano',
    'Palestrina',
    'Palombara Sabina',
    'Percile',
    'Pisoniano',
    'Poli',
    'Pomezia',
    'Ponzano Romano',
    'Riano',
    'Rignano Flaminio',
    'Riofreddo',
    'Rocca Canterano',
    'Rocca di Cave',
    'Rocca di Papa',
    'Rocca Priora',
    'Rocca Santo Stefano',
    'Roccagiovine',
    'Roiate',
    'Roviano',
    'Sacrofano',
    'Sambuci',
    'San Cesareo',
    'San Gregorio da Sassola',
    'San Polo dei Cavalieri',
    'San Vito Romano',
    'Santa Marinella',
    "Sant'Angelo Romano",
    "Sant'Oreste",
    'Saracinesco',
    'Segni',
    'Subiaco',
    'Tivoli',
    'Tolfa',
    'Torrita Tiberina',
    'Trevignano Romano',
    'Vallepietra',
    'Vallinfreda',
    'Valmontone',
    'Velletri',
    'Vicovaro',
    'Vivaro Romano',
    'Zagarolo',
  ],
};

export type ItalyLocations = {
  regions: string[];
  provincesByRegion: Record<string, string[]>;
  citiesByProvince: Record<string, string[]>;
};

export const FALLBACK_ITALY_LOCATIONS: ItalyLocations = {
  regions: [...ITALY_REGIONS],
  provincesByRegion: PROVINCES_BY_REGION,
  citiesByProvince: CITIES_BY_PROVINCE,
};
