import { NextRequest } from 'next/server';
import { withAuth } from '@/lib/api/auth';
import { NextResponse } from 'next/server';
import { validateOrganizationMembership, OrganizationMembershipError } from '@/lib/sports/organizationMembership.server';
const errorJson=(message:string,status:number)=>NextResponse.json({error:message},{status});

async function clubProfile(supabase:any,userId:string){const club=(await supabase.from('profiles').select('id,country').eq('user_id',userId).eq('account_type','club').single()).data;if(!club)return null;const preference=(await supabase.from('profile_preferences').select('residence_country_id').eq('profile_id',club.id).maybeSingle()).data;if(preference?.residence_country_id)return {...club,countryId:preference.residence_country_id};const mapping=club.country?(await supabase.from('legacy_country_mappings').select('country_id').eq('normalized_source_value',club.country.trim().toLowerCase()).eq('is_active',true).maybeSingle()).data:null;return {...club,countryId:mapping?.country_id??null};}
export const GET=withAuth(async(_req,{supabase,user})=>{const club=await clubProfile(supabase,user.id);if(!club)return errorJson('club_only',403);const [{data,error},{data:legacyMappings,error:mappingsError}]=await Promise.all([supabase.from('club_sport_registrations').select('*,sports:sport_id(code,canonical_name),organization:sports_organization_id(code,canonical_name),category:sports_organization_category_id(canonical_name)').eq('club_profile_id',club.id).eq('is_active',true).order('is_primary',{ascending:false}).order('created_at'),supabase.from('legacy_sport_mappings').select('legacy_display_label,sport_id,discipline_id,variant_id').eq('is_active',true)]);if(error||mappingsError)return errorJson((error??mappingsError)!.message,400);const rows=(data??[]).map((registration:any)=>({...registration,legacy_sport:(legacyMappings??[]).find((mapping:any)=>mapping.sport_id===registration.sport_id&&(mapping.discipline_id??null)===(registration.sport_discipline_id??null)&&(mapping.variant_id??null)===(registration.sport_variant_id??null))?.legacy_display_label??registration.sports?.canonical_name??''}));return NextResponse.json({data:rows,countryId:club.countryId});});
export const POST=withAuth(async(req:NextRequest,{supabase,user})=>{const club=await clubProfile(supabase,user.id);if(!club)return errorJson('club_only',403);if(!club.countryId)return errorJson('club_country_required',400);const b=await req.json();try{await validateOrganizationMembership(supabase,{organizationId:b.sports_organization_id,categoryId:b.sports_organization_category_id,sportId:b.sport_id,disciplineId:b.sport_discipline_id??null,variantId:b.sport_variant_id??null,countryId:club.countryId});}catch(e){return errorJson(e instanceof OrganizationMembershipError?e.code:'invalid_registration',400);}const {data,error}=await supabase.from('club_sport_registrations').insert({...b,club_profile_id:club.id}).select('*').single();return error?errorJson(error.message,400):NextResponse.json({data});});
