import sponsorMessages from './sponsor/en';
import completion from './completion/en';
import type { MessageKey } from './it';
import feedMessages from './feed/en';
import operationsMessages from './operations/en';
import vocabularyMessages from './vocabulary/en';
const messages = {
  ...sponsorMessages,
  ...completion,
  ...operationsMessages,
  ...vocabularyMessages,
  'common.loading':'Loading…','common.continue':'Continue','common.save':'Save','common.cancel':'Cancel','common.search':'Search','common.profile':'Profile','common.settings':'Settings','common.logout':'Log out','common.login':'Log in','common.language':'Language','common.skipContent':'Skip to main content','common.privacy':'Privacy','common.terms':'Terms','common.betaInfo':'Beta notice',
  'navigation.feed':'Feed','navigation.opportunities':'Opportunities','navigation.applications':'Applications','navigation.messages':'Messages','navigation.clubMap':'Club map','navigation.notifications':'Notifications','navigation.following':'Following','navigation.whoToFollow':'Who to follow','navigation.roster':'Roster','navigation.staff':'Staff','navigation.editProfile':'Edit profile','navigation.verifyProfile':'Verify profile','navigation.createOpportunity':'Create opportunity','navigation.openMenu':'Open navigation menu','navigation.closeMenu':'Close navigation menu','navigation.searchPlaceholder':'Search clubs, players, opportunities, posts, events…',
  'language.select':'Choose language','language.saveError':'The language could not be saved. Your previous selection was restored; please try again.',
  'auth.loginTitle':'Log in','auth.email':'Email','auth.password':'Password','auth.forgotPassword':'Forgot password?','auth.signingIn':'Signing in…','auth.enter':'Log in','auth.or':'or','auth.continueApple':'Continue with Apple','auth.continueGoogle':'Continue with Google','auth.wait':'Please wait…','auth.socialError':'Could not sign in with {provider}.','auth.recoverPassword':'Recover password','auth.acceptTerms':'By signing in, you accept the Terms of Use and Privacy Policy.','auth.loggedAs':'You are signed in as {email}.','auth.registerGoogle':'Sign up with Google','auth.registerApple':'Sign up with Apple','auth.signupTitle':'Join Club and Player','auth.signupIntro':'Sign up as a Club, Player, Institution, Staff member or Fan and build your sports network.','auth.createAccount':'Create an account','auth.nameOptional':'Name (optional)','auth.confirmPassword':'Confirm password','auth.registering':'Signing up…','auth.register':'Sign up','auth.alreadyAccount':'Already have an account?','auth.passwordTooShort':'Your password must be at least 8 characters.','auth.passwordMismatch':'The passwords do not match.','auth.signupSuccess':'Registration started! Check your email to confirm your account.','auth.benefitDiscover':'Discover and publish real opportunities','auth.benefitProfile':'Build a clear, up-to-date profile','auth.benefitMessages':'Receive applications and in-app messages','auth.downloadApp':'Download the app','auth.secureAccess':'Secure access with email or social login','auth.signupAccept':'By signing up, you accept the Terms of Use and Privacy Policy.',
  'roles.heading':'Choose how you want to use Club and Player','roles.subtitle':'Each role offers a different experience','roles.institution':'INSTITUTION','roles.club':'CLUB','roles.player':'PLAYER','roles.staff':'STAFF','roles.fan':'FAN','roles.institutionDescription':'Federations, governing bodies, committees, delegations and leagues with document verification','roles.clubDescription':'Manage your Club, publish content and create opportunities','roles.playerDescription':'Live your sport, build your profile and find opportunities','roles.staffDescription':'Build your professional profile and find new opportunities','roles.fanDescription':'Follow and support Clubs and Players on and off the field','roles.saving':'Saving…','roles.saveError':'Could not save',
  'opportunities.reverseOrder':'Reverse order','opportunities.visitClubProfile':'Visit Club profile','opportunities.deleteTitle':'Delete opportunity?','opportunities.deleteConfirm':'Do you want to delete “{title}”?',  'discovery.title':'Who to follow','discovery.subtitle':'Suggestions for you','discovery.goFollowing':'View profiles you follow','opportunities.title':'Opportunities','opportunities.country':'Country','opportunities.region':'Region','opportunities.province':'Province','opportunities.city':'City','opportunities.sport':'Sport','opportunities.role':'Role/position','opportunities.selectSport':'Select a sport','opportunities.allRoleGroups':'Role group: All','opportunities.category':'Category/level','opportunities.age':'Age','opportunities.sort':'Sort','opportunities.recent':'Newest','opportunities.oldest':'Oldest','opportunities.perPage':'Per page','opportunities.loadError':'Loading error','opportunities.clubOnly':'You must be a Club to create an opportunity.','search.title':'Search','search.country':'Country','search.allCountries':'All countries','search.region':'Region','search.allRegions':'All regions','search.province':'Province','search.allProvinces':'All provinces','search.city':'City','search.allCities':'All cities','search.sport':'Sport','search.allSports':'All sports','search.role':'Role','search.allRoles':'All roles','search.loadingResults':'Loading results…','search.all':'All','search.institutions':'Institutions','search.clubs':'Clubs','search.players':'Players','search.staff':'Staff','search.posts':'Posts','search.events':'Events','errors.generic':'Something went wrong. Please try again.','empty.noResults':'No results found.', ...feedMessages
} satisfies Record<MessageKey,string>;
export default messages;
