import sponsorMessages from './sponsor/es';
import completion from './completion/es';
import type { MessageKey } from './it';
import feedMessages from './feed/es';
import operationsMessages from './operations/es';
import vocabularyMessages from './vocabulary/es';
const messages = {
  ...sponsorMessages,
  ...completion,
  ...operationsMessages,
  ...vocabularyMessages,
  'common.loading':'Cargando…','common.continue':'Continuar','common.save':'Guardar','common.cancel':'Cancelar','common.search':'Buscar','common.profile':'Perfil','common.settings':'Ajustes','common.logout':'Cerrar sesión','common.login':'Iniciar sesión','common.language':'Idioma','common.skipContent':'Saltar al contenido principal','common.privacy':'Privacidad','common.terms':'Términos','common.betaInfo':'Información beta',
  'navigation.feed':'Inicio','navigation.opportunities':'Oportunidades','navigation.applications':'Candidaturas','navigation.messages':'Mensajes','navigation.clubMap':'Mapa de Clubes','navigation.notifications':'Notificaciones','navigation.following':'Siguiendo','navigation.whoToFollow':'A quién seguir','navigation.roster':'Plantilla','navigation.staff':'Cuerpo técnico','navigation.editProfile':'Editar perfil','navigation.verifyProfile':'Verificar perfil','navigation.createOpportunity':'Crear oportunidad','navigation.openMenu':'Abrir menú de navegación','navigation.closeMenu':'Cerrar menú de navegación','navigation.searchPlaceholder':'Buscar Clubes, jugadores, oportunidades, publicaciones, eventos…',
  'language.select':'Elegir idioma','language.saveError':'No se pudo guardar la preferencia remota. Tu elección sigue activa en este dispositivo.',
  'auth.loginTitle':'Iniciar sesión','auth.email':'Correo electrónico','auth.password':'Contraseña','auth.forgotPassword':'¿Has olvidado la contraseña?','auth.signingIn':'Iniciando sesión…','auth.enter':'Entrar','auth.or':'o','auth.continueApple':'Continuar con Apple','auth.continueGoogle':'Continuar con Google','auth.wait':'Espera…','auth.socialError':'No se pudo iniciar sesión con {provider}.','auth.recoverPassword':'Recuperar contraseña','auth.acceptTerms':'Al iniciar sesión, aceptas los Términos de uso y la Política de privacidad.','auth.loggedAs':'Has iniciado sesión como {email}.','auth.registerGoogle':'Registrarse con Google','auth.registerApple':'Registrarse con Apple','auth.signupTitle':'Únete a Club and Player','auth.signupIntro':'Regístrate como Club, Jugador, Institución, miembro del Staff o Aficionado y crea tu red deportiva.','auth.createAccount':'Crear una cuenta','auth.nameOptional':'Nombre (opcional)','auth.confirmPassword':'Confirmar contraseña','auth.registering':'Registrando…','auth.register':'Registrarse','auth.alreadyAccount':'¿Ya tienes una cuenta?','auth.passwordTooShort':'La contraseña debe tener al menos 8 caracteres.','auth.passwordMismatch':'Las contraseñas no coinciden.','auth.signupSuccess':'¡Registro iniciado! Consulta tu correo para confirmar la cuenta.','auth.benefitDiscover':'Descubre y publica oportunidades reales','auth.benefitProfile':'Crea un perfil claro y actualizado','auth.benefitMessages':'Recibe candidaturas y mensajes en la aplicación','auth.downloadApp':'Descarga la aplicación','auth.secureAccess':'Acceso seguro con correo o inicio de sesión social','auth.signupAccept':'Al registrarte, aceptas los Términos de uso y la Política de privacidad.',
  'roles.heading':'Elige cómo quieres usar Club and Player','roles.subtitle':'Cada rol ofrece una experiencia diferente','roles.institution':'INSTITUCIÓN','roles.club':'CLUB','roles.player':'JUGADOR','roles.staff':'CUERPO TÉCNICO','roles.fan':'AFICIONADO','roles.institutionDescription':'Federaciones, organismos, comités, delegaciones y ligas con verificación documental','roles.clubDescription':'Gestiona tu Club, publica contenido y crea oportunidades','roles.playerDescription':'Vive tu deporte, crea tu perfil y encuentra oportunidades','roles.staffDescription':'Crea tu perfil profesional y encuentra nuevas oportunidades','roles.fanDescription':'Sigue y apoya a Clubes y Jugadores dentro y fuera del campo','roles.saving':'Guardando…','roles.saveError':'No se pudo guardar',
  'discovery.title':'A quién seguir','discovery.subtitle':'Sugerencias para ti','discovery.goFollowing':'Ver perfiles seguidos','opportunities.title':'Oportunidades','opportunities.country':'País','opportunities.region':'Región','opportunities.province':'Provincia','opportunities.city':'Ciudad','opportunities.sport':'Deporte','opportunities.role':'Rol/posición','opportunities.selectSport':'Selecciona un deporte','opportunities.allRoleGroups':'Grupo de rol: Todos','opportunities.category':'Categoría/nivel','opportunities.age':'Edad','opportunities.sort':'Ordenar','opportunities.recent':'Más recientes','opportunities.oldest':'Más antiguas','opportunities.perPage':'Por página','opportunities.loadError':'Error de carga','opportunities.clubOnly':'Debes ser un Club para crear una oportunidad.','search.title':'Buscar','search.country':'País','search.allCountries':'Todos los países','search.region':'Región','search.allRegions':'Todas las regiones','search.province':'Provincia','search.allProvinces':'Todas las provincias','search.city':'Ciudad','search.allCities':'Todas las ciudades','search.sport':'Deporte','search.allSports':'Todos los deportes','search.role':'Rol','search.allRoles':'Todos los roles','search.loadingResults':'Cargando resultados…','search.all':'Todos','search.institutions':'Instituciones','search.clubs':'Clubes','search.players':'Jugadores','search.staff':'Cuerpo técnico','search.posts':'Publicaciones','search.events':'Eventos','errors.generic':'Se ha producido un error. Inténtalo de nuevo.','empty.noResults':'No se encontraron resultados.', ...feedMessages
} satisfies Record<MessageKey,string>;
export default messages;
