import sponsorMessages from './sponsor/fr';
import completion from './completion/fr';
import type { MessageKey } from './it';
import feedMessages from './feed/fr';
import operationsMessages from './operations/fr';
import vocabularyMessages from './vocabulary/fr';
const messages = {
  ...sponsorMessages,
  ...completion,
  ...operationsMessages,
  ...vocabularyMessages,
  'common.loading':'Chargement…','common.continue':'Continuer','common.save':'Enregistrer','common.cancel':'Annuler','common.search':'Rechercher','common.profile':'Profil','common.settings':'Paramètres','common.logout':'Déconnexion','common.login':'Se connecter','common.language':'Langue','common.skipContent':'Aller au contenu principal','common.privacy':'Confidentialité','common.terms':'Conditions','common.betaInfo':'Informations sur la version bêta',
  'navigation.feed':'Fil','navigation.opportunities':'Opportunités','navigation.applications':'Candidatures','navigation.messages':'Messages','navigation.clubMap':'Carte des Clubs','navigation.notifications':'Notifications','navigation.following':'Abonnements','navigation.whoToFollow':'Qui suivre','navigation.roster':'Effectif','navigation.staff':'Staff','navigation.editProfile':'Modifier le profil','navigation.verifyProfile':'Vérifier le profil','navigation.createOpportunity':'Créer une opportunité','navigation.openMenu':'Ouvrir le menu de navigation','navigation.closeMenu':'Fermer le menu de navigation','navigation.searchPlaceholder':'Rechercher des Clubs, joueurs, opportunités, publications, événements…',
  'language.select':'Choisir la langue','language.saveError':'La langue n’a pas pu être enregistrée. La sélection précédente a été restaurée ; réessayez.',
  'auth.loginTitle':'Connexion','auth.email':'E-mail','auth.password':'Mot de passe','auth.forgotPassword':'Mot de passe oublié ?','auth.signingIn':'Connexion…','auth.enter':'Se connecter','auth.or':'ou','auth.continueApple':'Continuer avec Apple','auth.continueGoogle':'Continuer avec Google','auth.wait':'Veuillez patienter…','auth.socialError':'La connexion avec {provider} a échoué.','auth.recoverPassword':'Récupérer le mot de passe','auth.acceptTerms':'En vous connectant, vous acceptez les Conditions d’utilisation et la Politique de confidentialité.','auth.loggedAs':'Vous êtes connecté sous {email}.','auth.registerGoogle':'S’inscrire avec Google','auth.registerApple':'S’inscrire avec Apple','auth.signupTitle':'Rejoignez Club and Player','auth.signupIntro':'Inscrivez-vous comme Club, Joueur, Institution, membre du Staff ou Supporter et développez votre réseau sportif.','auth.createAccount':'Créer un compte','auth.nameOptional':'Nom (facultatif)','auth.confirmPassword':'Confirmer le mot de passe','auth.registering':'Inscription…','auth.register':'S’inscrire','auth.alreadyAccount':'Vous avez déjà un compte ?','auth.passwordTooShort':'Le mot de passe doit contenir au moins 8 caractères.','auth.passwordMismatch':'Les mots de passe ne correspondent pas.','auth.signupSuccess':'Inscription lancée ! Consultez votre e-mail pour confirmer votre compte.','auth.benefitDiscover':'Découvrez et publiez de vraies opportunités','auth.benefitProfile':'Créez un profil clair et à jour','auth.benefitMessages':'Recevez des candidatures et des messages dans l’application','auth.downloadApp':'Télécharger l’application','auth.secureAccess':'Accès sécurisé par e-mail ou connexion sociale','auth.signupAccept':'En vous inscrivant, vous acceptez les Conditions d’utilisation et la Politique de confidentialité.',
  'roles.heading':'Choisissez comment utiliser Club and Player','roles.subtitle':'Chaque rôle offre une expérience différente','roles.institution':'INSTITUTION','roles.club':'CLUB','roles.player':'JOUEUR','roles.staff':'STAFF','roles.fan':'SUPPORTER','roles.institutionDescription':'Fédérations, organismes, comités, délégations et ligues avec vérification documentaire','roles.clubDescription':'Gérez votre Club, publiez du contenu et créez des opportunités','roles.playerDescription':'Vivez votre sport, créez votre profil et trouvez des opportunités','roles.staffDescription':'Créez votre profil professionnel et trouvez de nouvelles opportunités','roles.fanDescription':'Suivez et soutenez les Clubs et les Joueurs sur le terrain et en dehors','roles.saving':'Enregistrement…','roles.saveError':'Échec de l’enregistrement',
  'discovery.title':'Qui suivre','discovery.subtitle':'Suggestions pour vous','discovery.goFollowing':'Voir les profils suivis','opportunities.title':'Opportunités','opportunities.country':'Pays','opportunities.region':'Région','opportunities.province':'Province','opportunities.city':'Ville','opportunities.sport':'Sport','opportunities.role':'Rôle ou poste','opportunities.selectSport':'Sélectionnez un sport','opportunities.allRoleGroups':'Groupe de rôles : Tous','opportunities.category':'Catégorie/niveau','opportunities.age':'Âge','opportunities.sort':'Trier','opportunities.recent':'Plus récentes','opportunities.oldest':'Plus anciennes','opportunities.perPage':'Par page','opportunities.loadError':'Erreur de chargement','opportunities.clubOnly':'Vous devez être un Club pour créer une opportunité.','search.title':'Recherche','search.country':'Pays','search.allCountries':'Tous les pays','search.region':'Région','search.allRegions':'Toutes les régions','search.province':'Province','search.allProvinces':'Toutes les provinces','search.city':'Ville','search.allCities':'Toutes les villes','search.sport':'Sport','search.allSports':'Tous les sports','search.role':'Rôle','search.allRoles':'Tous les rôles','search.loadingResults':'Chargement des résultats…','search.all':'Tous','search.institutions':'Institutions','search.clubs':'Clubs','search.players':'Joueurs','search.staff':'Staff','search.posts':'Publications','search.events':'Événements','errors.generic':'Une erreur est survenue. Réessayez.','empty.noResults':'Aucun résultat trouvé.', ...feedMessages
} satisfies Record<MessageKey,string>;
export default messages;
