import type { VocabularyMessageKey } from './it';
const vocabulary: Record<VocabularyMessageKey, string> = {
  'vocabulary.account.player':'Player','vocabulary.account.club':'Club','vocabulary.account.staff':'Staff','vocabulary.account.fan':'Fan','vocabulary.account.institution':'Institution / Federation',
  'vocabulary.sport.football':'Football','vocabulary.sport.eightAsideFootball':'Eight-a-side football','vocabulary.sport.futsal':'Futsal','vocabulary.sport.volleyball':'Volleyball','vocabulary.sport.basketball':'Basketball','vocabulary.sport.waterPolo':'Water polo','vocabulary.sport.handball':'Handball','vocabulary.sport.rugby':'Rugby','vocabulary.sport.fieldHockey':'Field hockey','vocabulary.sport.iceHockey':'Ice hockey','vocabulary.sport.baseball':'Baseball','vocabulary.sport.softball':'Softball','vocabulary.sport.lacrosse':'Lacrosse','vocabulary.sport.americanFootball':'American football',
  'vocabulary.gender.male':'Men','vocabulary.gender.female':'Women','vocabulary.gender.mixed':'Mixed',
  'vocabulary.category.first':'First Division','vocabulary.category.second':'Second Division','vocabulary.category.third':'Third Division','vocabulary.category.amateur':'Amateur','vocabulary.category.youth':'Youth','vocabulary.category.other':'Other',
  'vocabulary.role.goalkeeper':'Goalkeeper','vocabulary.role.defender':'Defender','vocabulary.role.centreBack':'Centre-back','vocabulary.role.fullBack':'Full-back / Wing-back','vocabulary.role.defensiveMidfielder':'Defensive midfielder','vocabulary.role.midfielder':'Midfielder','vocabulary.role.centralMidfielder':'Central midfielder','vocabulary.role.attackingMidfielder':'Attacking midfielder','vocabulary.role.winger':'Winger','vocabulary.role.forward':'Forward','vocabulary.role.secondStriker':'Second striker','vocabulary.role.centreForward':'Centre-forward','vocabulary.role.playmaker':'Playmaker','vocabulary.role.fixo':'Fixo','vocabulary.role.pivot':'Pivot','vocabulary.role.universal':'Universal','vocabulary.role.setter':'Setter','vocabulary.role.opposite':'Opposite hitter','vocabulary.role.outsideHitter':'Outside hitter','vocabulary.role.middleBlocker':'Middle blocker','vocabulary.role.libero':'Libero','vocabulary.role.coach':'Coach','vocabulary.role.scout':'Scout','vocabulary.role.sportingDirector':'Sporting director',
  'vocabulary.status.open':'Open','vocabulary.status.closed':'Closed','vocabulary.status.draft':'Draft','vocabulary.status.archived':'Archived','vocabulary.status.pending':'Pending','vocabulary.status.inReview':'Under review','vocabulary.status.submitted':'Submitted','vocabulary.status.seen':'Seen','vocabulary.status.accepted':'Accepted','vocabulary.status.rejected':'Rejected','vocabulary.status.withdrawn':'Withdrawn','vocabulary.status.follow':'Follow','vocabulary.status.following':'Following','vocabulary.status.active':'Active','vocabulary.status.suspended':'Suspended',
}; export default vocabulary;
