import type { VocabularyMessageKey } from './it';
const vocabulary: Record<VocabularyMessageKey, string> = {
  'vocabulary.account.player':'Jugador','vocabulary.account.club':'Club','vocabulary.account.staff':'Cuerpo técnico','vocabulary.account.fan':'Aficionado','vocabulary.account.institution':'Institución / Federación',
  'vocabulary.sport.football':'Fútbol','vocabulary.sport.eightAsideFootball':'Fútbol 8','vocabulary.sport.futsal':'Fútbol sala','vocabulary.sport.volleyball':'Voleibol','vocabulary.sport.basketball':'Baloncesto','vocabulary.sport.waterPolo':'Waterpolo','vocabulary.sport.handball':'Balonmano','vocabulary.sport.rugby':'Rugby','vocabulary.sport.fieldHockey':'Hockey sobre césped','vocabulary.sport.iceHockey':'Hockey sobre hielo','vocabulary.sport.baseball':'Béisbol','vocabulary.sport.softball':'Sóftbol','vocabulary.sport.lacrosse':'Lacrosse','vocabulary.sport.americanFootball':'Fútbol americano',
  'vocabulary.gender.male':'Hombres','vocabulary.gender.female':'Mujeres','vocabulary.gender.mixed':'Mixto',
  'vocabulary.category.first':'Primera Categoría','vocabulary.category.second':'Segunda Categoría','vocabulary.category.third':'Tercera Categoría','vocabulary.category.amateur':'Aficionado','vocabulary.category.youth':'Categorías juveniles','vocabulary.category.other':'Otro',
  'vocabulary.role.goalkeeper':'Portero','vocabulary.role.defender':'Defensa','vocabulary.role.centreBack':'Defensa central','vocabulary.role.fullBack':'Lateral / Carrilero','vocabulary.role.defensiveMidfielder':'Mediocentro defensivo','vocabulary.role.midfielder':'Centrocampista','vocabulary.role.centralMidfielder':'Centrocampista central','vocabulary.role.attackingMidfielder':'Mediapunta','vocabulary.role.winger':'Extremo','vocabulary.role.forward':'Delantero','vocabulary.role.secondStriker':'Segundo delantero','vocabulary.role.centreForward':'Delantero centro','vocabulary.role.playmaker':'Organizador','vocabulary.role.fixo':'Cierre','vocabulary.role.pivot':'Pívot','vocabulary.role.universal':'Universal','vocabulary.role.setter':'Colocador','vocabulary.role.opposite':'Opuesto','vocabulary.role.outsideHitter':'Receptor-atacante','vocabulary.role.middleBlocker':'Central','vocabulary.role.libero':'Líbero','vocabulary.role.coach':'Entrenador','vocabulary.role.scout':'Ojeador','vocabulary.role.sportingDirector':'Director deportivo',
  'vocabulary.status.open':'Abierto','vocabulary.status.closed':'Cerrado','vocabulary.status.draft':'Borrador','vocabulary.status.archived':'Archivado','vocabulary.status.pending':'Pendiente','vocabulary.status.inReview':'En evaluación','vocabulary.status.submitted':'Enviada','vocabulary.status.seen':'Vista','vocabulary.status.accepted':'Aceptada','vocabulary.status.rejected':'Rechazada','vocabulary.status.withdrawn':'Retirada','vocabulary.status.follow':'Seguir','vocabulary.status.following':'Siguiendo','vocabulary.status.active':'Activo','vocabulary.status.suspended':'Suspendido',
}; export default vocabulary;
