'use client';

import { useI18n } from '@/components/i18n/I18nProvider';
import type { Locale } from '@/lib/i18n/config';

type DocumentKind = 'privacy' | 'terms' | 'beta' | 'childSafety';
type Section = { title: string; paragraphs?: string[]; items?: string[] };
type DocumentCopy = { title: string; intro?: string; sections: Section[]; contact?: string; updated: string };

const email = (address: string) => <a className="underline" href={`mailto:${address}`}>{address}</a>;

const documents: Record<Locale, Record<DocumentKind, DocumentCopy>> = {
  it: {
    privacy: { title: 'Informativa Privacy', intro: 'Questa informativa descrive come Club and Player tratta i dati personali e come puoi esercitare i tuoi diritti ai sensi del GDPR.', sections: [
      { title: 'Titolare e contatti', paragraphs: ['Il titolare del trattamento è Club and Player. Per richieste sulla privacy scrivi a privacy@clubandplayer.com.'] },
      { title: 'Dati trattati e finalità', items: ['Dati anagrafici e di contatto forniti durante la registrazione.', 'Dati del profilo, contenuti, candidature, messaggi e preferenze inseriti volontariamente.', 'Log tecnici necessari per sicurezza e assistenza.', 'Metriche aggregate raccolte tramite analytics privacy-first.'], paragraphs: ['Trattiamo i dati per erogare il servizio, garantirne la sicurezza e migliorarlo. Il marketing e gli aggiornamenti Beta richiedono il consenso.'] },
      { title: 'Fornitori, cookie e sicurezza', paragraphs: ['Utilizziamo Supabase per autenticazione, database e storage, Vercel per hosting e API, Resend per email transazionali e analytics privacy-first solo dopo il consenso.', 'Adottiamo controlli di accesso, Row Level Security e misure tecniche adeguate. Conserviamo i dati per la durata del rapporto o per gli obblighi di legge.'] },
      { title: 'I tuoi diritti', paragraphs: ['Puoi chiedere accesso, rettifica, cancellazione, limitazione, opposizione e portabilità scrivendo a privacy@clubandplayer.com. Puoi richiedere l’eliminazione dell’account a support@clubandplayer.com.'] },
      { title: 'Programma Beta privata', paragraphs: ['I feedback Beta possono essere associati al profilo per velocizzare il supporto. Puoi lasciare il programma scrivendo a beta@clubandplayer.com.'] },
    ], updated: 'Ultimo aggiornamento' },
    terms: { title: 'Termini e condizioni d’uso', intro: 'Usando Club and Player accetti questi Termini e, se partecipi alla Beta privata, le relative condizioni supplementari.', sections: [
      { title: 'Oggetto del servizio', paragraphs: ['Club and Player offre strumenti di incontro tra società sportive e atleti, messaggistica e gestione delle opportunità. Le funzionalità possono cambiare per ragioni tecniche o di sicurezza.'] },
      { title: 'Uso consentito', items: ['Non utilizzare il servizio per attività illecite, spam o scraping non autorizzato.', 'Gli account dei Club devono rappresentare organizzazioni reali con dati aggiornati.', 'Non aggirare i controlli di sicurezza o accedere senza permesso.'] },
      { title: 'Contenuti e sicurezza', paragraphs: ['Sei responsabile dei contenuti caricati e devi possederne i diritti. Non tolleriamo contenuti offensivi, abusivi, discriminatori, minacciosi o illegali. Gli utenti possono segnalare contenuti e bloccare profili; possiamo rimuovere contenuti o sospendere account.'] },
      { title: 'Limitazione di responsabilità', paragraphs: ['Il servizio è fornito “così com’è”. Nei limiti di legge non rispondiamo di danni indiretti o perdita di opportunità. La responsabilità complessiva è limitata alle somme pagate negli ultimi 12 mesi.'] },
      { title: 'Privacy e Beta', paragraphs: ['Si applica l’Informativa Privacy. Le funzioni Beta possono essere modificate o rimosse; i feedback possono essere usati per migliorare il prodotto.'] },
    ], updated: 'Ultimo aggiornamento' },
    beta: { title: 'Informativa programma Beta', intro: 'Questa pagina riassume diritti e doveri degli utenti invitati alla Beta privata e integra Termini e Privacy.', sections: [
      { title: 'Chi può partecipare', paragraphs: ['La Beta è riservata agli utenti invitati. Gli account sono personali, non trasferibili e revocabili in caso di uso improprio.'] },
      { title: 'Cosa monitoriamo', paragraphs: ['Raccogliamo feedback e log strettamente necessari per diagnosticare errori. I dati seguono l’Informativa Privacy e vengono cancellati quando non servono più.'] },
      { title: 'Feedback e uscita', paragraphs: ['Puoi scrivere a beta@clubandplayer.com in qualsiasi momento. Gestiamo l’uscita entro 48 ore e, su richiesta, eliminiamo i contenuti Beta.'] },
      { title: 'Aggiornamenti', paragraphs: ['Le nuove build e le regressioni note vengono comunicate via email o nel changelog.'] },
    ], contact: 'Per qualsiasi dubbio scrivi a', updated: 'Ultimo aggiornamento' },
    childSafety: { title: 'Standard di sicurezza dei minori', sections: [
      { title: 'La nostra tutela', paragraphs: ['Club and Player è dedicata ad atleti e Club e non è destinata ai minori di 13 anni.', 'Non è consentito pubblicare o condividere contenuti che coinvolgano minori in modo improprio o illegale.'], items: ['Possibilità di segnalare utenti e contenuti.', 'Monitoraggio delle attività sospette.', 'Rimozione dei contenuti che violano le regole.'] },
    ], contact: 'Per segnalazioni relative alla sicurezza scrivi a', updated: 'Ultimo aggiornamento' },
  },
  en: {
    privacy: { title: 'Privacy Policy', intro: 'This policy explains how Club and Player processes personal data and how you can exercise your GDPR rights.', sections: [
      { title: 'Controller and contact', paragraphs: ['Club and Player is the data controller. Email privacy@clubandplayer.com for privacy requests.'] }, { title: 'Data and purposes', items: ['Registration and contact details.', 'Profile data, content, applications, messages and preferences you provide.', 'Technical logs needed for security and support.', 'Aggregated privacy-first analytics.'], paragraphs: ['We process data to provide, secure and improve the service. Marketing and Beta updates require consent.'] }, { title: 'Providers, cookies and security', paragraphs: ['We use Supabase for authentication, database and storage, Vercel for hosting and APIs, Resend for transactional email, and privacy-first analytics only after consent.', 'We use access controls and Row Level Security and retain data for the service relationship or legal obligations.'] }, { title: 'Your rights', paragraphs: ['You may request access, correction, deletion, restriction, objection and portability at privacy@clubandplayer.com. Request account deletion at support@clubandplayer.com.'] }, { title: 'Private Beta', paragraphs: ['Beta feedback may be linked to your profile to speed up support. Leave the programme by emailing beta@clubandplayer.com.'] },
    ], updated: 'Last updated' },
    terms: { title: 'Terms and Conditions of Use', intro: 'By using Club and Player you accept these Terms and, if applicable, the additional Private Beta conditions.', sections: [
      { title: 'The service', paragraphs: ['Club and Player provides sports matching, messaging and opportunity management tools. Features may change for technical or security reasons.'] }, { title: 'Acceptable use', items: ['Do not use the service for unlawful activity, spam or unauthorised scraping.', 'Club accounts must represent real organisations and keep details current.', 'Do not bypass security controls or access restricted areas without permission.'] }, { title: 'Content and safety', paragraphs: ['You are responsible for uploaded content and must own the necessary rights. Offensive, abusive, discriminatory, threatening or illegal content is not tolerated. Users can report content and block profiles; we may remove content or suspend accounts.'] }, { title: 'Liability', paragraphs: ['The service is provided “as is”. To the extent permitted by law, we are not liable for indirect loss or lost opportunities. Total liability is limited to fees paid in the previous 12 months.'] }, { title: 'Privacy and Beta', paragraphs: ['The Privacy Policy applies. Beta features may change or be removed and feedback may be used to improve the product.'] },
    ], updated: 'Last updated' },
    beta: { title: 'Beta Programme Notice', intro: 'This page summarises the rights and duties of Private Beta invitees and supplements the Terms and Privacy Policy.', sections: [{ title: 'Who may participate', paragraphs: ['The Beta is invitation-only. Accounts are personal, non-transferable and may be revoked for misuse.'] }, { title: 'What we monitor', paragraphs: ['We collect feedback and logs strictly needed to diagnose errors. Data follows the Privacy Policy and is deleted when no longer needed.'] }, { title: 'Feedback and leaving', paragraphs: ['Email beta@clubandplayer.com at any time. Exit requests are handled within 48 hours and Beta content can be deleted on request.'] }, { title: 'Updates', paragraphs: ['New builds and known regressions are announced by email or in the changelog.'] }], contact: 'For any questions email', updated: 'Last updated' },
    childSafety: { title: 'Child Safety Standards', sections: [{ title: 'Our safeguards', paragraphs: ['Club and Player is designed for athletes and Clubs and is not intended for children under 13.', 'Content involving minors in an improper or illegal manner is prohibited.'], items: ['Users and content can be reported.', 'Suspicious activity is monitored.', 'Content that violates our rules is removed.'] }], contact: 'For safety reports email', updated: 'Last updated' },
  },
  fr: {} as Record<DocumentKind, DocumentCopy>,
  es: {} as Record<DocumentKind, DocumentCopy>,
};

documents.fr = {
  privacy: { ...documents.en.privacy, title: 'Politique de confidentialité', intro: 'Cette politique explique comment Club and Player traite les données personnelles et comment exercer vos droits RGPD.', sections: [{ title: 'Responsable et contact', paragraphs: ['Club and Player est responsable du traitement. Écrivez à privacy@clubandplayer.com pour toute demande.'] }, { title: 'Données et finalités', items: ['Données d’inscription et de contact.', 'Profil, contenus, candidatures, messages et préférences fournis.', 'Journaux techniques nécessaires à la sécurité.', 'Mesures agrégées respectueuses de la vie privée.'], paragraphs: ['Nous traitons les données pour fournir, sécuriser et améliorer le service. Le marketing et les actualités Bêta nécessitent votre consentement.'] }, { title: 'Prestataires, cookies et sécurité', paragraphs: ['Nous utilisons Supabase, Vercel, Resend et des statistiques privacy-first après consentement. Nous appliquons des contrôles d’accès et conservons les données selon la durée du service et les obligations légales.'] }, { title: 'Vos droits', paragraphs: ['Demandez accès, rectification, effacement, limitation, opposition ou portabilité à privacy@clubandplayer.com. Pour supprimer le compte : support@clubandplayer.com.'] }, { title: 'Bêta privée', paragraphs: ['Les retours peuvent être liés au profil. Quittez le programme via beta@clubandplayer.com.'] }], updated: 'Dernière mise à jour' },
  terms: { ...documents.en.terms, title: 'Conditions générales d’utilisation', intro: 'En utilisant Club and Player, vous acceptez ces Conditions et, le cas échéant, celles de la Bêta privée.', sections: [{ title: 'Le service', paragraphs: ['Club and Player propose des outils de mise en relation sportive, de messagerie et de gestion d’opportunités.'] }, { title: 'Utilisation autorisée', items: ['Aucune activité illégale, spam ou extraction non autorisée.', 'Les comptes Club doivent représenter des organisations réelles.', 'Ne contournez pas les contrôles de sécurité.'] }, { title: 'Contenus et sécurité', paragraphs: ['Vous êtes responsable de vos contenus et de leurs droits. Les contenus offensants, abusifs, discriminatoires, menaçants ou illégaux sont interdits. Nous pouvons les supprimer ou suspendre des comptes.'] }, { title: 'Responsabilité', paragraphs: ['Le service est fourni « tel quel ». Dans les limites légales, la responsabilité totale est limitée aux montants payés durant les 12 derniers mois.'] }, { title: 'Vie privée et Bêta', paragraphs: ['La Politique de confidentialité s’applique. Les fonctions Bêta peuvent changer et les retours servir à améliorer le produit.'] }], updated: 'Dernière mise à jour' },
  beta: { title: 'Information sur le programme Bêta', intro: 'Cette page résume les droits et devoirs des invités à la Bêta privée.', sections: [{ title: 'Participation', paragraphs: ['La Bêta est sur invitation. Les comptes sont personnels et non transférables.'] }, { title: 'Suivi', paragraphs: ['Nous recueillons uniquement les retours et journaux nécessaires au diagnostic, conformément à la Politique de confidentialité.'] }, { title: 'Retours et sortie', paragraphs: ['Écrivez à beta@clubandplayer.com. Les sorties sont traitées sous 48 heures.'] }, { title: 'Mises à jour', paragraphs: ['Les builds et régressions connues sont annoncées par email ou changelog.'] }], contact: 'Pour toute question, écrivez à', updated: 'Dernière mise à jour' },
  childSafety: { title: 'Normes de sécurité des mineurs', sections: [{ title: 'Nos protections', paragraphs: ['Club and Player est destiné aux athlètes et Clubs et non aux enfants de moins de 13 ans.', 'Tout contenu impliquant des mineurs de manière inappropriée ou illégale est interdit.'], items: ['Signalement des utilisateurs et contenus.', 'Surveillance des activités suspectes.', 'Suppression des contenus contraires aux règles.'] }], contact: 'Pour un signalement de sécurité, écrivez à', updated: 'Dernière mise à jour' },
};

documents.es = {
  privacy: { ...documents.en.privacy, title: 'Política de privacidad', intro: 'Esta política explica cómo Club and Player trata los datos personales y cómo ejercer tus derechos del RGPD.', sections: [{ title: 'Responsable y contacto', paragraphs: ['Club and Player es el responsable del tratamiento. Escribe a privacy@clubandplayer.com para solicitudes de privacidad.'] }, { title: 'Datos y finalidades', items: ['Datos de registro y contacto.', 'Perfil, contenidos, candidaturas, mensajes y preferencias aportados.', 'Registros técnicos necesarios para seguridad.', 'Métricas agregadas respetuosas con la privacidad.'], paragraphs: ['Tratamos los datos para prestar, proteger y mejorar el servicio. El marketing y las novedades Beta requieren consentimiento.'] }, { title: 'Proveedores, cookies y seguridad', paragraphs: ['Usamos Supabase, Vercel, Resend y analítica privacy-first tras el consentimiento. Aplicamos controles de acceso y conservamos los datos durante la relación o por obligaciones legales.'] }, { title: 'Tus derechos', paragraphs: ['Solicita acceso, rectificación, supresión, limitación, oposición o portabilidad en privacy@clubandplayer.com. Para eliminar la cuenta: support@clubandplayer.com.'] }, { title: 'Beta privada', paragraphs: ['Los comentarios pueden vincularse al perfil. Sal del programa escribiendo a beta@clubandplayer.com.'] }], updated: 'Última actualización' },
  terms: { ...documents.en.terms, title: 'Términos y condiciones de uso', intro: 'Al usar Club and Player aceptas estos Términos y, cuando corresponda, las condiciones de la Beta privada.', sections: [{ title: 'El servicio', paragraphs: ['Club and Player ofrece herramientas de conexión deportiva, mensajería y gestión de oportunidades.'] }, { title: 'Uso permitido', items: ['No uses el servicio para actividades ilegales, spam o extracción no autorizada.', 'Las cuentas de Club deben representar organizaciones reales.', 'No eludas controles de seguridad.'] }, { title: 'Contenido y seguridad', paragraphs: ['Eres responsable del contenido y sus derechos. No se tolera contenido ofensivo, abusivo, discriminatorio, amenazante o ilegal. Podemos retirarlo o suspender cuentas.'] }, { title: 'Responsabilidad', paragraphs: ['El servicio se ofrece “tal cual”. Dentro de los límites legales, la responsabilidad total se limita a los importes pagados en los últimos 12 meses.'] }, { title: 'Privacidad y Beta', paragraphs: ['Se aplica la Política de privacidad. Las funciones Beta pueden cambiar y los comentarios pueden mejorar el producto.'] }], updated: 'Última actualización' },
  beta: { title: 'Información del programa Beta', intro: 'Esta página resume los derechos y deberes de quienes reciben una invitación a la Beta privada.', sections: [{ title: 'Participación', paragraphs: ['La Beta es solo por invitación. Las cuentas son personales e intransferibles.'] }, { title: 'Qué supervisamos', paragraphs: ['Recopilamos únicamente comentarios y registros necesarios para diagnosticar errores, según la Política de privacidad.'] }, { title: 'Comentarios y salida', paragraphs: ['Escribe a beta@clubandplayer.com. Las solicitudes de salida se gestionan en 48 horas.'] }, { title: 'Actualizaciones', paragraphs: ['Las nuevas versiones y regresiones conocidas se anuncian por email o changelog.'] }], contact: 'Para cualquier duda escribe a', updated: 'Última actualización' },
  childSafety: { title: 'Normas de seguridad infantil', sections: [{ title: 'Nuestras medidas', paragraphs: ['Club and Player está dirigido a deportistas y Clubes y no a menores de 13 años.', 'Está prohibido el contenido que involucre a menores de forma inapropiada o ilegal.'], items: ['Denuncia de usuarios y contenidos.', 'Supervisión de actividad sospechosa.', 'Retirada del contenido que incumpla las normas.'] }], contact: 'Para avisos de seguridad escribe a', updated: 'Última actualización' },
};

export default function LocalizedLegalDocument({ kind }: { kind: DocumentKind }) {
  const { locale } = useI18n();
  const copy = documents[locale][kind];
  const contactAddress = kind === 'beta' ? 'beta@clubandplayer.com' : 'support@clubandplayer.com';
  return <main className="container mx-auto max-w-3xl px-4 py-8">
    <h1 className="mb-4 text-3xl font-semibold">{copy.title}</h1>
    {copy.intro ? <p className="text-sm leading-6 text-neutral-600 dark:text-neutral-300">{copy.intro}</p> : null}
    <div className="mt-8 space-y-8 text-sm text-neutral-700 dark:text-neutral-200">
      {copy.sections.map((section) => <section key={section.title} className="space-y-3">
        <h2 className="text-lg font-semibold">{section.title}</h2>
        {section.paragraphs?.map((paragraph) => <p key={paragraph} className="leading-6">{paragraph}</p>)}
        {section.items ? <ul className="list-disc space-y-2 pl-6">{section.items.map((item) => <li key={item}>{item}</li>)}</ul> : null}
      </section>)}
    </div>
    {copy.contact ? <section className="mt-10 rounded-md border border-sky-200 bg-sky-50 px-4 py-4 text-sm text-sky-900">{copy.contact}{' '}{email(contactAddress)}</section> : null}
    <p className="mt-10 text-xs uppercase tracking-wide text-neutral-500">{copy.updated}: {new Intl.DateTimeFormat(locale).format(new Date())}</p>
  </main>;
}
