export type ProvinceAbbreviationMap = Record<string, string>;

const ITALIAN_PROVINCE_ENTRIES = [
  ['agrigento', 'AG'],
  ['alessandria', 'AL'],
  ['ancona', 'AN'],
  ['aosta', 'AO'],
  ["l'aquila", 'AQ'],
  ['aquila', 'AQ'],
  ['arezzo', 'AR'],
  ['ascoli piceno', 'AP'],
  ['asti', 'AT'],
  ['avellino', 'AV'],
  ['bari', 'BA'],
  ['barletta-andria-trani', 'BT'],
  ['barletta andria trani', 'BT'],
  ['belluno', 'BL'],
  ['benevento', 'BN'],
  ['bergamo', 'BG'],
  ['biella', 'BI'],
  ['bologna', 'BO'],
  ['bolzano', 'BZ'],
  ['bolzano/bozen', 'BZ'],
  ['brescia', 'BS'],
  ['brindisi', 'BR'],
  ['cagliari', 'CA'],
  ['caltanissetta', 'CL'],
  ['campobasso', 'CB'],
  ['caserta', 'CE'],
  ['catania', 'CT'],
  ['catanzaro', 'CZ'],
  ['chieti', 'CH'],
  ['como', 'CO'],
  ['cosenza', 'CS'],
  ['cremona', 'CR'],
  ['crotone', 'KR'],
  ['cuneo', 'CN'],
  ['enna', 'EN'],
  ['fermo', 'FM'],
  ['ferrara', 'FE'],
  ['firenze', 'FI'],
  ['foggia', 'FG'],
  ['forlì-cesena', 'FC'],
  ['forli-cesena', 'FC'],
  ['forli cesena', 'FC'],
  ['frosinone', 'FR'],
  ['genova', 'GE'],
  ['gorizia', 'GO'],
  ['grosseto', 'GR'],
  ['imperia', 'IM'],
  ['isernia', 'IS'],
  ['la spezia', 'SP'],
  ['latina', 'LT'],
  ['lecce', 'LE'],
  ['lecco', 'LC'],
  ['livorno', 'LI'],
  ['lodi', 'LO'],
  ['lucca', 'LU'],
  ['macerata', 'MC'],
  ['mantova', 'MN'],
  ['massa-carrara', 'MS'],
  ['massa carrara', 'MS'],
  ['matera', 'MT'],
  ['messina', 'ME'],
  ['milano', 'MI'],
  ['modena', 'MO'],
  ['monza e della brianza', 'MB'],
  ['monza-brianza', 'MB'],
  ['napoli', 'NA'],
  ['novara', 'NO'],
  ['nuoro', 'NU'],
  ['oristano', 'OR'],
  ['padova', 'PD'],
  ['palermo', 'PA'],
  ['parma', 'PR'],
  ['pavia', 'PV'],
  ['perugia', 'PG'],
  ['pesaro e urbino', 'PU'],
  ['pesaro-urbino', 'PU'],
  ['pescara', 'PE'],
  ['piacenza', 'PC'],
  ['pisa', 'PI'],
  ['pistoia', 'PT'],
  ['pordenone', 'PN'],
  ['potenza', 'PZ'],
  ['prato', 'PO'],
  ['ragusa', 'RG'],
  ['ravenna', 'RA'],
  ['reggio calabria', 'RC'],
  ['reggio emilia', 'RE'],
  ['rieti', 'RI'],
  ['rimini', 'RN'],
  ['roma', 'RM'],
  ['rovigo', 'RO'],
  ['salerno', 'SA'],
  ['sassari', 'SS'],
  ['savona', 'SV'],
  ['siena', 'SI'],
  ['siracusa', 'SR'],
  ['sondrio', 'SO'],
  ['sud sardegna', 'SU'],
  ['taranto', 'TA'],
  ['teramo', 'TE'],
  ['terni', 'TR'],
  ['torino', 'TO'],
  ['trapani', 'TP'],
  ['trento', 'TN'],
  ['treviso', 'TV'],
  ['trieste', 'TS'],
  ['udine', 'UD'],
  ['varese', 'VA'],
  ['venezia', 'VE'],
  ['verbano-cusio-ossola', 'VB'],
  ['verbano cusio ossola', 'VB'],
  ['vercelli', 'VC'],
  ['verona', 'VR'],
  ['vibo valentia', 'VV'],
  ['vicenza', 'VI'],
  ['viterbo', 'VT'],
] as const;

export const ITALIAN_PROVINCE_ABBREVIATIONS: ProvinceAbbreviationMap = Object.fromEntries(ITALIAN_PROVINCE_ENTRIES);

export function normalizeProvinceName(value?: string | null) {
  return (value ?? '')
    .trim()
    .toLowerCase()
    .replace(/[’']/g, "'")
    .replace(/\s+/g, ' ');
}

export function provinceDisplayValue(
  province: string | null | undefined,
  abbreviations?: ProvinceAbbreviationMap | null,
) {
  const currentValue = (province ?? '').trim();
  if (!currentValue) return '';
  const normalized = normalizeProvinceName(currentValue);
  const sigla = abbreviations?.[normalized]?.trim() || ITALIAN_PROVINCE_ABBREVIATIONS[normalized]?.trim();
  return sigla || currentValue;
}
