'use client';
import { useCallback,useEffect,useState } from 'react';
import CanonicalSportFilter,{type CanonicalSportFilterValue} from '@/components/sports/CanonicalSportFilter';
import OrganizationCategoryFields,{type OrganizationCategoryValue} from '@/components/sports/OrganizationCategoryFields';
import { sportsOrganizationDisplayName } from '@/lib/sports/organizationDisplay';
type Row={id:string;sport_id:string;sport_discipline_id:string|null;sport_variant_id:string|null;sports_organization_id:string;sports_organization_category_id:string;is_primary:boolean;sports?:{canonical_name:string};organization?:{code:string;canonical_name:string};category?:{canonical_name:string}};
const emptySport:CanonicalSportFilterValue={sportId:'',disciplineId:'',variantId:'',legacySport:''};
export default function ClubRegistrationsSection(){const [rows,setRows]=useState<Row[]>([]),[editing,setEditing]=useState<Row|null>(null),[open,setOpen]=useState(false),[sport,setSport]=useState(emptySport),[membership,setMembership]=useState<OrganizationCategoryValue>({organizationId:'',categoryId:''}),[primary,setPrimary]=useState(false);
const load=useCallback(()=>fetch('/api/clubs/registrations').then(r=>r.json()).then(j=>setRows(j.data??[])),[]);useEffect(()=>{load()},[load]);
function start(row?:Row){setEditing(row??null);setSport(row?{sportId:row.sport_id,disciplineId:row.sport_discipline_id??'',variantId:row.sport_variant_id??'',legacySport:''}:emptySport);setMembership(row?{organizationId:row.sports_organization_id,categoryId:row.sports_organization_category_id}:{organizationId:'',categoryId:''});setPrimary(row?.is_primary??rows.length===0);setOpen(true)}
async function save(){if(!sport.sportId||!membership.organizationId||!membership.categoryId)return;const body={sport_id:sport.sportId,sport_discipline_id:sport.disciplineId||null,sport_variant_id:sport.variantId||null,sports_organization_id:membership.organizationId,sports_organization_category_id:membership.categoryId,is_primary:primary,is_active:true};await fetch(editing?`/api/clubs/registrations/${editing.id}`:'/api/clubs/registrations',{method:editing?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});setOpen(false);await load()}
return <section className="rounded-2xl border bg-white p-5"><div className="flex justify-between"><h2 className="text-lg font-semibold">Iscrizioni</h2><button type="button" onClick={()=>start()} className="rounded-lg bg-blue-600 px-3 py-2 text-white">Aggiungi iscrizione</button></div><div className="mt-4 space-y-3">{rows.map(r=><div key={r.id} className="flex items-center justify-between rounded-xl border p-3"><div>{r.sports?.canonical_name??'Sport'} · {r.organization?sportsOrganizationDisplayName(r.organization.code,r.organization.canonical_name):'Ente'} · {r.category?.canonical_name??'Categoria'} {r.is_primary&&<b className="ml-2">Principale</b>}</div><div className="flex gap-2"><button type="button" onClick={()=>start(r)}>Modifica</button><button type="button" onClick={async()=>{await fetch(`/api/clubs/registrations/${r.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({is_active:false})});await load()}}>Disattiva</button></div></div>)}</div>{open&&<div className="mt-4 grid gap-3 md:grid-cols-3"><CanonicalSportFilter idPrefix="registration-sport" value={sport} onChange={(v,m)=>{setSport(v);if(m.source==='user')setMembership({organizationId:'',categoryId:''})}} labels={{sport:'Sport',allSports:'—',catalogUnavailable:'Catalogo non disponibile'}}/><OrganizationCategoryFields sport={sport} value={membership} onChange={setMembership} categoryLabel="Categoria/Campionato"/><label><input type="checkbox" checked={primary} onChange={e=>setPrimary(e.target.checked)}/> Imposta come iscrizione principale</label><button type="button" onClick={save}>Salva iscrizione</button><button type="button" onClick={()=>setOpen(false)}>Annulla</button></div>}</section>}
