begin;

-- Reconstructs the public schema that predates the first versioned migration.
-- Platform-managed auth/storage objects are intentionally not created here.
create extension if not exists pgcrypto;

create table if not exists public.regions (
  id bigint generated by default as identity primary key,
  name text not null
);
create table if not exists public.provinces (
  id bigint generated by default as identity primary key,
  region_id bigint references public.regions(id),
  name text not null,
  code text,
  sigla text
);
create table if not exists public.municipalities (
  id bigint generated by default as identity primary key,
  province_id bigint references public.provinces(id),
  region_id bigint references public.regions(id),
  name text not null
);

create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique references auth.users(id) on delete cascade,
  account_type text,
  type text,
  is_admin boolean not null default false,
  full_name text,
  display_name text,
  headline text,
  first_name text,
  last_name text,
  username text,
  email text,
  bio text,
  avatar_url text,
  cover_url text,
  links jsonb,
  birth_year integer,
  height_cm integer,
  weight_kg numeric,
  role text,
  sport text,
  category text,
  country text,
  region text,
  province text,
  city text,
  interest_country text,
  interest_region_id bigint references public.regions(id),
  interest_province_id bigint references public.provinces(id),
  interest_municipality_id bigint references public.municipalities(id),
  interest_region text,
  interest_province text,
  interest_city text,
  region_id bigint references public.regions(id),
  province_id bigint references public.provinces(id),
  city_id bigint references public.municipalities(id),
  nationality text,
  interests text[],
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.opportunities (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id) on delete cascade,
  created_by uuid references auth.users(id) on delete cascade,
  title text not null,
  description text,
  sport text,
  role text,
  gender text,
  age_range text,
  country text,
  region text,
  province text,
  city text,
  club_name text,
  status text default 'open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.clubs (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text,
  display_name text,
  city text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.saved_views (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text,
  filters jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references auth.users(id) on delete cascade,
  content text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.feed_posts (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null default 'system',
  created_at timestamptz not null default now()
);
create table if not exists public.follows (
  id uuid primary key default gen_random_uuid(),
  follower_id uuid not null references auth.users(id) on delete cascade,
  target_id uuid not null,
  target_type text not null default 'player',
  created_at timestamptz not null default now()
);
create table if not exists public.applications (
  id uuid primary key default gen_random_uuid(),
  opportunity_id uuid not null references public.opportunities(id) on delete cascade,
  athlete_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

commit;
