begin;

-- Phase 5D-C controlled vocabulary and exact legacy compatibility only.
-- No profiles, experiences, opportunities, applications, organizations, competitions,
-- user data, ownership, RLS, grants, or schema objects are modified.

insert into public.gender_categories (code, canonical_name, is_active, display_order)
values
  ('male', 'Male', true, 10),
  ('female', 'Female', true, 20),
  ('mixed', 'Mixed', true, 30)
on conflict (code) do nothing;

insert into public.competition_formats (code, canonical_name, is_active, display_order)
values
  ('round_robin', 'Round robin', true, 10),
  ('knockout', 'Knockout', true, 20),
  ('group_then_knockout', 'Group stage then knockout', true, 30),
  ('hybrid', 'Hybrid', true, 40)
on conflict (code) do nothing;

insert into public.territorial_scopes (code, canonical_name, requires_country, allows_multiple_countries, allows_geo_area, is_active, display_order)
values
  ('global', 'Global', false, true, false, true, 10),
  ('continental', 'Continental', false, true, false, true, 20),
  ('multi_country', 'Multi-country', false, true, false, true, 30),
  ('national', 'National', true, false, false, true, 40),
  ('subnational', 'Subnational', true, false, true, true, 50),
  ('local', 'Local', true, false, true, true, 60)
on conflict (code) do nothing;

insert into public.player_positions (code, canonical_name, is_active, display_order)
values
  ('association_football_goalkeeper', 'Association football goalkeeper', true, 10),
  ('association_football_centre_back', 'Association football centre-back', true, 20),
  ('association_football_full_back', 'Association football full-back or wing-back', true, 30),
  ('association_football_defensive_midfielder', 'Association football defensive midfielder', true, 40),
  ('association_football_central_midfielder', 'Association football central midfielder', true, 50),
  ('association_football_attacking_midfielder', 'Association football attacking midfielder', true, 60),
  ('association_football_winger', 'Association football winger', true, 70),
  ('association_football_second_striker', 'Association football second striker', true, 80),
  ('association_football_centre_forward', 'Association football centre-forward', true, 90),
  ('eight_a_side_goalkeeper', 'Eight-a-side goalkeeper', true, 10),
  ('eight_a_side_central_defender', 'Eight-a-side central defender', true, 20),
  ('eight_a_side_wide_defender', 'Eight-a-side wide defender', true, 30),
  ('eight_a_side_playmaker', 'Eight-a-side playmaker', true, 40),
  ('eight_a_side_wide_attacker', 'Eight-a-side wide attacker', true, 50),
  ('eight_a_side_centre_forward', 'Eight-a-side centre-forward', true, 60),
  ('futsal_goalkeeper', 'Futsal goalkeeper', true, 10),
  ('futsal_fixo', 'Futsal fixo', true, 20),
  ('futsal_winger', 'Futsal winger', true, 30),
  ('futsal_pivot', 'Futsal pivot', true, 40),
  ('futsal_universal', 'Futsal universal', true, 50),
  ('volleyball_setter', 'Volleyball setter', true, 10),
  ('volleyball_opposite', 'Volleyball opposite', true, 20),
  ('volleyball_outside_hitter', 'Volleyball outside hitter', true, 30),
  ('volleyball_middle_blocker', 'Volleyball middle blocker', true, 40),
  ('volleyball_libero', 'Volleyball libero', true, 50),
  ('basketball_point_guard', 'Basketball point guard', true, 10),
  ('basketball_shooting_guard', 'Basketball shooting guard', true, 20),
  ('basketball_small_forward', 'Basketball small forward', true, 30),
  ('basketball_power_forward', 'Basketball power forward', true, 40),
  ('basketball_center', 'Basketball center', true, 50),
  ('water_polo_goalkeeper', 'Water polo goalkeeper', true, 10),
  ('water_polo_center_forward', 'Water polo center forward', true, 20),
  ('water_polo_center_back', 'Water polo center back', true, 30),
  ('water_polo_driver', 'Water polo driver', true, 40),
  ('water_polo_wing', 'Water polo wing', true, 50),
  ('water_polo_point', 'Water polo point', true, 60),
  ('handball_goalkeeper', 'Handball goalkeeper', true, 10),
  ('handball_left_wing', 'Handball left wing', true, 20),
  ('handball_left_back', 'Handball left back', true, 30),
  ('handball_center_back', 'Handball center back', true, 40),
  ('handball_right_back', 'Handball right back', true, 50),
  ('handball_right_wing', 'Handball right wing', true, 60),
  ('handball_pivot', 'Handball pivot', true, 70),
  ('rugby_prop', 'Rugby prop', true, 10),
  ('rugby_hooker', 'Rugby hooker', true, 20),
  ('rugby_lock', 'Rugby lock', true, 30),
  ('rugby_flanker', 'Rugby flanker', true, 40),
  ('rugby_number_eight', 'Rugby number eight', true, 50),
  ('rugby_scrum_half', 'Rugby scrum-half', true, 60),
  ('rugby_fly_half', 'Rugby fly-half', true, 70),
  ('rugby_center', 'Rugby center', true, 80),
  ('rugby_wing', 'Rugby wing', true, 90),
  ('rugby_fullback', 'Rugby fullback', true, 100),
  ('field_hockey_goalkeeper', 'Field hockey goalkeeper', true, 10),
  ('field_hockey_defender', 'Field hockey defender', true, 20),
  ('field_hockey_midfielder', 'Field hockey midfielder', true, 30),
  ('field_hockey_forward', 'Field hockey forward', true, 40),
  ('ice_hockey_goaltender', 'Ice hockey goaltender', true, 10),
  ('ice_hockey_defenseman', 'Ice hockey defenseman', true, 20),
  ('ice_hockey_left_wing', 'Ice hockey left wing', true, 30),
  ('ice_hockey_center', 'Ice hockey center', true, 40),
  ('ice_hockey_right_wing', 'Ice hockey right wing', true, 50),
  ('baseball_pitcher', 'Baseball pitcher', true, 10),
  ('baseball_catcher', 'Baseball catcher', true, 20),
  ('baseball_first_base', 'Baseball first baseman', true, 30),
  ('baseball_second_base', 'Baseball second baseman', true, 40),
  ('baseball_third_base', 'Baseball third baseman', true, 50),
  ('baseball_shortstop', 'Baseball shortstop', true, 60),
  ('baseball_left_fielder', 'Baseball left fielder', true, 70),
  ('baseball_center_fielder', 'Baseball center fielder', true, 80),
  ('baseball_right_fielder', 'Baseball right fielder', true, 90),
  ('baseball_designated_hitter', 'Baseball designated hitter', true, 100),
  ('softball_pitcher', 'Softball pitcher', true, 10),
  ('softball_catcher', 'Softball catcher', true, 20),
  ('softball_first_base', 'Softball first baseman', true, 30),
  ('softball_second_base', 'Softball second baseman', true, 40),
  ('softball_third_base', 'Softball third baseman', true, 50),
  ('softball_shortstop', 'Softball shortstop', true, 60),
  ('softball_left_fielder', 'Softball left fielder', true, 70),
  ('softball_center_fielder', 'Softball center fielder', true, 80),
  ('softball_right_fielder', 'Softball right fielder', true, 90),
  ('lacrosse_goalkeeper', 'Lacrosse goalkeeper', true, 10),
  ('lacrosse_defender', 'Lacrosse defender', true, 20),
  ('lacrosse_midfielder', 'Lacrosse midfielder', true, 30),
  ('lacrosse_attack', 'Lacrosse attack', true, 40),
  ('lacrosse_long_stick_midfielder', 'Lacrosse long-stick midfielder', true, 50),
  ('lacrosse_faceoff_specialist', 'Lacrosse faceoff specialist', true, 60),
  ('american_football_quarterback', 'American football quarterback', true, 10),
  ('american_football_running_back', 'American football running back', true, 20),
  ('american_football_wide_receiver', 'American football wide receiver', true, 30),
  ('american_football_tight_end', 'American football tight end', true, 40),
  ('american_football_offensive_lineman', 'American football offensive lineman', true, 50),
  ('american_football_defensive_lineman', 'American football defensive lineman', true, 60),
  ('american_football_linebacker', 'American football linebacker', true, 70),
  ('american_football_cornerback', 'American football cornerback', true, 80),
  ('american_football_safety', 'American football safety', true, 90),
  ('american_football_kicker_punter', 'American football kicker or punter', true, 100)
on conflict (code) do nothing;

insert into public.staff_roles (code, canonical_name, is_active, display_order)
values
  ('president', 'President', true, 10),
  ('vice_president', 'Vice president', true, 20),
  ('sporting_director', 'Sporting director', true, 30),
  ('general_manager', 'General manager', true, 40),
  ('secretary', 'Secretary', true, 50),
  ('team_manager', 'Team manager', true, 60),
  ('team_official', 'Team official', true, 70),
  ('head_coach', 'Head coach', true, 80),
  ('assistant_coach', 'Assistant coach', true, 90),
  ('technical_assistant', 'Technical assistant', true, 100),
  ('match_analyst', 'Match analyst', true, 110),
  ('video_analyst', 'Video analyst', true, 120),
  ('strength_conditioning_coach', 'Strength and conditioning coach', true, 130),
  ('goalkeeping_coach', 'Goalkeeping coach', true, 140),
  ('team_doctor', 'Team doctor', true, 150),
  ('physiotherapist', 'Physiotherapist', true, 160),
  ('osteopath', 'Osteopath', true, 170),
  ('massage_therapist', 'Massage therapist', true, 180),
  ('mental_performance_coach', 'Mental performance coach', true, 190),
  ('nutritionist', 'Nutritionist', true, 200),
  ('scout', 'Scout', true, 210),
  ('talent_scout', 'Talent scout', true, 220),
  ('press_officer', 'Press officer', true, 230),
  ('social_media_manager', 'Social media manager', true, 240),
  ('photographer', 'Photographer', true, 250),
  ('content_creator', 'Content creator', true, 260)
on conflict (code) do nothing;

with seed(position_code, sport_code, discipline_code, variant_code) as (
  values
    ('association_football_goalkeeper', 'football', 'association_football', 'eleven_a_side'),
  ('association_football_centre_back', 'football', 'association_football', 'eleven_a_side'),
  ('association_football_full_back', 'football', 'association_football', 'eleven_a_side'),
  ('association_football_defensive_midfielder', 'football', 'association_football', 'eleven_a_side'),
  ('association_football_central_midfielder', 'football', 'association_football', 'eleven_a_side'),
  ('association_football_attacking_midfielder', 'football', 'association_football', 'eleven_a_side'),
  ('association_football_winger', 'football', 'association_football', 'eleven_a_side'),
  ('association_football_second_striker', 'football', 'association_football', 'eleven_a_side'),
  ('association_football_centre_forward', 'football', 'association_football', 'eleven_a_side'),
  ('eight_a_side_goalkeeper', 'football', 'association_football', 'eight_a_side'),
  ('eight_a_side_central_defender', 'football', 'association_football', 'eight_a_side'),
  ('eight_a_side_wide_defender', 'football', 'association_football', 'eight_a_side'),
  ('eight_a_side_playmaker', 'football', 'association_football', 'eight_a_side'),
  ('eight_a_side_wide_attacker', 'football', 'association_football', 'eight_a_side'),
  ('eight_a_side_centre_forward', 'football', 'association_football', 'eight_a_side'),
  ('futsal_goalkeeper', 'football', 'futsal', null),
  ('futsal_fixo', 'football', 'futsal', null),
  ('futsal_winger', 'football', 'futsal', null),
  ('futsal_pivot', 'football', 'futsal', null),
  ('futsal_universal', 'football', 'futsal', null),
  ('volleyball_setter', 'volleyball', null, null),
  ('volleyball_opposite', 'volleyball', null, null),
  ('volleyball_outside_hitter', 'volleyball', null, null),
  ('volleyball_middle_blocker', 'volleyball', null, null),
  ('volleyball_libero', 'volleyball', null, null),
  ('basketball_point_guard', 'basketball', null, null),
  ('basketball_shooting_guard', 'basketball', null, null),
  ('basketball_small_forward', 'basketball', null, null),
  ('basketball_power_forward', 'basketball', null, null),
  ('basketball_center', 'basketball', null, null),
  ('water_polo_goalkeeper', 'water_polo', null, null),
  ('water_polo_center_forward', 'water_polo', null, null),
  ('water_polo_center_back', 'water_polo', null, null),
  ('water_polo_driver', 'water_polo', null, null),
  ('water_polo_wing', 'water_polo', null, null),
  ('water_polo_point', 'water_polo', null, null),
  ('handball_goalkeeper', 'handball', null, null),
  ('handball_left_wing', 'handball', null, null),
  ('handball_left_back', 'handball', null, null),
  ('handball_center_back', 'handball', null, null),
  ('handball_right_back', 'handball', null, null),
  ('handball_right_wing', 'handball', null, null),
  ('handball_pivot', 'handball', null, null),
  ('rugby_prop', 'rugby', null, null),
  ('rugby_hooker', 'rugby', null, null),
  ('rugby_lock', 'rugby', null, null),
  ('rugby_flanker', 'rugby', null, null),
  ('rugby_number_eight', 'rugby', null, null),
  ('rugby_scrum_half', 'rugby', null, null),
  ('rugby_fly_half', 'rugby', null, null),
  ('rugby_center', 'rugby', null, null),
  ('rugby_wing', 'rugby', null, null),
  ('rugby_fullback', 'rugby', null, null),
  ('field_hockey_goalkeeper', 'field_hockey', null, null),
  ('field_hockey_defender', 'field_hockey', null, null),
  ('field_hockey_midfielder', 'field_hockey', null, null),
  ('field_hockey_forward', 'field_hockey', null, null),
  ('ice_hockey_goaltender', 'ice_hockey', null, null),
  ('ice_hockey_defenseman', 'ice_hockey', null, null),
  ('ice_hockey_left_wing', 'ice_hockey', null, null),
  ('ice_hockey_center', 'ice_hockey', null, null),
  ('ice_hockey_right_wing', 'ice_hockey', null, null),
  ('baseball_pitcher', 'baseball', null, null),
  ('baseball_catcher', 'baseball', null, null),
  ('baseball_first_base', 'baseball', null, null),
  ('baseball_second_base', 'baseball', null, null),
  ('baseball_third_base', 'baseball', null, null),
  ('baseball_shortstop', 'baseball', null, null),
  ('baseball_left_fielder', 'baseball', null, null),
  ('baseball_center_fielder', 'baseball', null, null),
  ('baseball_right_fielder', 'baseball', null, null),
  ('baseball_designated_hitter', 'baseball', null, null),
  ('softball_pitcher', 'softball', null, null),
  ('softball_catcher', 'softball', null, null),
  ('softball_first_base', 'softball', null, null),
  ('softball_second_base', 'softball', null, null),
  ('softball_third_base', 'softball', null, null),
  ('softball_shortstop', 'softball', null, null),
  ('softball_left_fielder', 'softball', null, null),
  ('softball_center_fielder', 'softball', null, null),
  ('softball_right_fielder', 'softball', null, null),
  ('lacrosse_goalkeeper', 'lacrosse', null, null),
  ('lacrosse_defender', 'lacrosse', null, null),
  ('lacrosse_midfielder', 'lacrosse', null, null),
  ('lacrosse_attack', 'lacrosse', null, null),
  ('lacrosse_long_stick_midfielder', 'lacrosse', null, null),
  ('lacrosse_faceoff_specialist', 'lacrosse', null, null),
  ('american_football_quarterback', 'american_football', null, null),
  ('american_football_running_back', 'american_football', null, null),
  ('american_football_wide_receiver', 'american_football', null, null),
  ('american_football_tight_end', 'american_football', null, null),
  ('american_football_offensive_lineman', 'american_football', null, null),
  ('american_football_defensive_lineman', 'american_football', null, null),
  ('american_football_linebacker', 'american_football', null, null),
  ('american_football_cornerback', 'american_football', null, null),
  ('american_football_safety', 'american_football', null, null),
  ('american_football_kicker_punter', 'american_football', null, null)
)
insert into public.player_position_applicability (position_id, sport_id, discipline_id, variant_id)
select p.id, s.id, d.id, v.id
from seed
join public.player_positions p on p.code = seed.position_code
join public.sports s on s.code = seed.sport_code
left join public.sport_disciplines d on d.sport_id = s.id and d.code = seed.discipline_code
left join public.sport_variants v on v.discipline_id = d.id and v.code = seed.variant_code
where (seed.discipline_code is null or d.id is not null)
  and (seed.variant_code is null or v.id is not null)
on conflict (position_id, sport_id, discipline_id, variant_id) do nothing;

with seed(source_value, normalized_source_value, sport_code, discipline_code, variant_code, position_code, notes) as (
  values
    ('Portiere', 'portiere', 'football', 'association_football', 'eleven_a_side', 'association_football_goalkeeper', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Difensore centrale', 'difensore_centrale', 'football', 'association_football', 'eleven_a_side', 'association_football_centre_back', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Terzino/Esterno difensivo', 'terzino_esterno_difensivo', 'football', 'association_football', 'eleven_a_side', 'association_football_full_back', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Mediano', 'mediano', 'football', 'association_football', 'eleven_a_side', 'association_football_defensive_midfielder', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Centrocampista centrale', 'centrocampista_centrale', 'football', 'association_football', 'eleven_a_side', 'association_football_central_midfielder', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Trequartista', 'trequartista', 'football', 'association_football', 'eleven_a_side', 'association_football_attacking_midfielder', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Esterno offensivo/Ala', 'esterno_offensivo_ala', 'football', 'association_football', 'eleven_a_side', 'association_football_winger', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Seconda punta', 'seconda_punta', 'football', 'association_football', 'eleven_a_side', 'association_football_second_striker', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Punta centrale', 'punta_centrale', 'football', 'association_football', 'eleven_a_side', 'association_football_centre_forward', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Portiere', 'portiere', 'football', 'association_football', 'eight_a_side', 'eight_a_side_goalkeeper', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Difensore Centrale', 'difensore_centrale', 'football', 'association_football', 'eight_a_side', 'eight_a_side_central_defender', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Esterno Basso', 'esterno_basso', 'football', 'association_football', 'eight_a_side', 'eight_a_side_wide_defender', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Regista', 'regista', 'football', 'association_football', 'eight_a_side', 'eight_a_side_playmaker', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Esterno Alto', 'esterno_alto', 'football', 'association_football', 'eight_a_side', 'eight_a_side_wide_attacker', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Punta Centrale', 'punta_centrale', 'football', 'association_football', 'eight_a_side', 'eight_a_side_centre_forward', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Portiere', 'portiere', 'football', 'futsal', null, 'futsal_goalkeeper', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Fixo', 'fixo', 'football', 'futsal', null, 'futsal_fixo', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Ala', 'ala', 'football', 'futsal', null, 'futsal_winger', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Pivot', 'pivot', 'football', 'futsal', null, 'futsal_pivot', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Universale', 'universale', 'football', 'futsal', null, 'futsal_universal', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Palleggiatore', 'palleggiatore', 'volleyball', null, null, 'volleyball_setter', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Opposto', 'opposto', 'volleyball', null, null, 'volleyball_opposite', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Schiacciatore', 'schiacciatore', 'volleyball', null, null, 'volleyball_outside_hitter', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Centrale', 'centrale', 'volleyball', null, null, 'volleyball_middle_blocker', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Libero', 'libero', 'volleyball', null, null, 'volleyball_libero', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Playmaker (PG)', 'playmaker_pg', 'basketball', null, null, 'basketball_point_guard', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Guardia (SG)', 'guardia_sg', 'basketball', null, null, 'basketball_shooting_guard', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Ala piccola (SF)', 'ala_piccola_sf', 'basketball', null, null, 'basketball_small_forward', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Ala grande (PF)', 'ala_grande_pf', 'basketball', null, null, 'basketball_power_forward', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Centro (C)', 'centro_c', 'basketball', null, null, 'basketball_center', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Portiere', 'portiere', 'water_polo', null, null, 'water_polo_goalkeeper', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Centroboa', 'centroboa', 'water_polo', null, null, 'water_polo_center_forward', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Marcatore (Hole-D)', 'marcatore_hole_d', 'water_polo', null, null, 'water_polo_center_back', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Driver/Perimetrale', 'driver_perimetrale', 'water_polo', null, null, 'water_polo_driver', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Ala', 'ala', 'water_polo', null, null, 'water_polo_wing', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Punto/Regista', 'punto_regista', 'water_polo', null, null, 'water_polo_point', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Portiere', 'portiere', 'handball', null, null, 'handball_goalkeeper', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Ala sinistra', 'ala_sinistra', 'handball', null, null, 'handball_left_wing', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Terzino sinistro', 'terzino_sinistro', 'handball', null, null, 'handball_left_back', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Centrale', 'centrale', 'handball', null, null, 'handball_center_back', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Terzino destro', 'terzino_destro', 'handball', null, null, 'handball_right_back', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Ala destra', 'ala_destra', 'handball', null, null, 'handball_right_wing', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Pivot', 'pivot', 'handball', null, null, 'handball_pivot', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Pilone', 'pilone', 'rugby', null, null, 'rugby_prop', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Tallonatore', 'tallonatore', 'rugby', null, null, 'rugby_hooker', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Seconda linea', 'seconda_linea', 'rugby', null, null, 'rugby_lock', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Flanker', 'flanker', 'rugby', null, null, 'rugby_flanker', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Numero 8', 'numero_8', 'rugby', null, null, 'rugby_number_eight', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Mediano di mischia', 'mediano_di_mischia', 'rugby', null, null, 'rugby_scrum_half', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Apertura', 'apertura', 'rugby', null, null, 'rugby_fly_half', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Centro', 'centro', 'rugby', null, null, 'rugby_center', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Ala', 'ala', 'rugby', null, null, 'rugby_wing', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Estremo', 'estremo', 'rugby', null, null, 'rugby_fullback', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Portiere', 'portiere', 'field_hockey', null, null, 'field_hockey_goalkeeper', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Difensore', 'difensore', 'field_hockey', null, null, 'field_hockey_defender', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Centrocampista', 'centrocampista', 'field_hockey', null, null, 'field_hockey_midfielder', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Attaccante', 'attaccante', 'field_hockey', null, null, 'field_hockey_forward', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Portiere', 'portiere', 'ice_hockey', null, null, 'ice_hockey_goaltender', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Difensore', 'difensore', 'ice_hockey', null, null, 'ice_hockey_defenseman', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Ala sinistra', 'ala_sinistra', 'ice_hockey', null, null, 'ice_hockey_left_wing', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Centro', 'centro', 'ice_hockey', null, null, 'ice_hockey_center', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Ala destra', 'ala_destra', 'ice_hockey', null, null, 'ice_hockey_right_wing', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Pitcher', 'pitcher', 'baseball', null, null, 'baseball_pitcher', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Catcher', 'catcher', 'baseball', null, null, 'baseball_catcher', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Prima base', 'prima_base', 'baseball', null, null, 'baseball_first_base', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Seconda base', 'seconda_base', 'baseball', null, null, 'baseball_second_base', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Terza base', 'terza_base', 'baseball', null, null, 'baseball_third_base', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Interbase', 'interbase', 'baseball', null, null, 'baseball_shortstop', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Esterno sinistro', 'esterno_sinistro', 'baseball', null, null, 'baseball_left_fielder', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Esterno centro', 'esterno_centro', 'baseball', null, null, 'baseball_center_fielder', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Esterno destro', 'esterno_destro', 'baseball', null, null, 'baseball_right_fielder', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Battitore designato', 'battitore_designato', 'baseball', null, null, 'baseball_designated_hitter', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Pitcher', 'pitcher', 'softball', null, null, 'softball_pitcher', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Catcher', 'catcher', 'softball', null, null, 'softball_catcher', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Prima base', 'prima_base', 'softball', null, null, 'softball_first_base', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Seconda base', 'seconda_base', 'softball', null, null, 'softball_second_base', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Terza base', 'terza_base', 'softball', null, null, 'softball_third_base', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Interbase', 'interbase', 'softball', null, null, 'softball_shortstop', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Esterno sinistro', 'esterno_sinistro', 'softball', null, null, 'softball_left_fielder', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Esterno centro', 'esterno_centro', 'softball', null, null, 'softball_center_fielder', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Esterno destro', 'esterno_destro', 'softball', null, null, 'softball_right_fielder', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Portiere', 'portiere', 'lacrosse', null, null, 'lacrosse_goalkeeper', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Difensore', 'difensore', 'lacrosse', null, null, 'lacrosse_defender', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Centrocampista', 'centrocampista', 'lacrosse', null, null, 'lacrosse_midfielder', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Attaccante', 'attaccante', 'lacrosse', null, null, 'lacrosse_attack', 'Phase 5D-C exact legacy compatibility mapping'),
  ('LSM', 'lsm', 'lacrosse', null, null, 'lacrosse_long_stick_midfielder', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Faceoff specialist', 'faceoff_specialist', 'lacrosse', null, null, 'lacrosse_faceoff_specialist', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Quarterback', 'quarterback', 'american_football', null, null, 'american_football_quarterback', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Running back', 'running_back', 'american_football', null, null, 'american_football_running_back', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Wide receiver', 'wide_receiver', 'american_football', null, null, 'american_football_wide_receiver', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Tight end', 'tight_end', 'american_football', null, null, 'american_football_tight_end', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Offensive lineman', 'offensive_lineman', 'american_football', null, null, 'american_football_offensive_lineman', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Defensive lineman', 'defensive_lineman', 'american_football', null, null, 'american_football_defensive_lineman', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Linebacker', 'linebacker', 'american_football', null, null, 'american_football_linebacker', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Cornerback', 'cornerback', 'american_football', null, null, 'american_football_cornerback', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Safety', 'safety', 'american_football', null, null, 'american_football_safety', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Kicker/Punter', 'kicker_punter', 'american_football', null, null, 'american_football_kicker_punter', 'Phase 5D-C exact legacy compatibility mapping')
)
insert into public.legacy_player_position_mappings
  (source_value, normalized_source_value, sport_id, discipline_id, variant_id, position_id, notes)
select seed.source_value, seed.normalized_source_value, s.id, d.id, v.id, p.id, seed.notes
from seed
join public.sports s on s.code = seed.sport_code
join public.player_positions p on p.code = seed.position_code
left join public.sport_disciplines d on d.sport_id = s.id and d.code = seed.discipline_code
left join public.sport_variants v on v.discipline_id = d.id and v.code = seed.variant_code
where (seed.discipline_code is null or d.id is not null)
  and (seed.variant_code is null or v.id is not null)
on conflict (normalized_source_value, sport_id, discipline_id, variant_id) do nothing;

with seed(source_value, normalized_source_value, staff_role_code, notes) as (
  values
    ('Presidente', 'presidente', 'president', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Vicepresidente', 'vicepresidente', 'vice_president', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Direttore Sportivo', 'direttore_sportivo', 'sporting_director', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Direttore Generale', 'direttore_generale', 'general_manager', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Segretario', 'segretario', 'secretary', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Team manager', 'team_manager', 'team_manager', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Dirigente Accompagnatore', 'dirigente_accompagnatore', 'team_official', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Allenatore', 'allenatore', 'head_coach', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Vice Allenatore', 'vice_allenatore', 'assistant_coach', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Collaboratore Tecnico', 'collaboratore_tecnico', 'technical_assistant', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Match Analyst', 'match_analyst', 'match_analyst', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Video Analyst', 'video_analyst', 'video_analyst', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Preparatore Atletico', 'preparatore_atletico', 'strength_conditioning_coach', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Preparatore Portieri', 'preparatore_portieri', 'goalkeeping_coach', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Medico Sociale', 'medico_sociale', 'team_doctor', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Fisioterapista', 'fisioterapista', 'physiotherapist', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Osteopata', 'osteopata', 'osteopath', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Massaggiatore', 'massaggiatore', 'massage_therapist', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Mental Coach', 'mental_coach', 'mental_performance_coach', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Nutrizionista', 'nutrizionista', 'nutritionist', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Scout', 'scout', 'scout', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Talent Scout', 'talent_scout', 'talent_scout', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Addetto Stampa', 'addetto_stampa', 'press_officer', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Social Media Manager', 'social_media_manager', 'social_media_manager', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Fotografo', 'fotografo', 'photographer', 'Phase 5D-C exact legacy compatibility mapping'),
  ('Content Creator', 'content_creator', 'content_creator', 'Phase 5D-C exact legacy compatibility mapping')
)
insert into public.legacy_staff_role_mappings (source_value, normalized_source_value, staff_role_id, notes)
select seed.source_value, seed.normalized_source_value, r.id, seed.notes
from seed
join public.staff_roles r on r.code = seed.staff_role_code
on conflict (normalized_source_value) do nothing;

do $$
begin
  if exists (select 1 from jsonb_to_recordset('[{"code":"male","canonical_name":"Male","display_order":10},{"code":"female","canonical_name":"Female","display_order":20},{"code":"mixed","canonical_name":"Mixed","display_order":30}]'::jsonb) as e(code text, canonical_name text, display_order integer) left join public.gender_categories t using (code) where t.code is null or t.canonical_name is distinct from e.canonical_name or t.display_order is distinct from e.display_order or t.is_active is distinct from true) then raise exception '5D-C gender_categories payload mismatch'; end if;
  if exists (select 1 from jsonb_to_recordset('[{"code":"round_robin","canonical_name":"Round robin","display_order":10},{"code":"knockout","canonical_name":"Knockout","display_order":20},{"code":"group_then_knockout","canonical_name":"Group stage then knockout","display_order":30},{"code":"hybrid","canonical_name":"Hybrid","display_order":40}]'::jsonb) as e(code text, canonical_name text, display_order integer) left join public.competition_formats t using (code) where t.code is null or t.canonical_name is distinct from e.canonical_name or t.display_order is distinct from e.display_order or t.is_active is distinct from true) then raise exception '5D-C competition_formats payload mismatch'; end if;
  if exists (select 1 from jsonb_to_recordset('[{"code":"global","canonical_name":"Global","requires_country":false,"allows_multiple_countries":true,"allows_geo_area":false,"display_order":10},{"code":"continental","canonical_name":"Continental","requires_country":false,"allows_multiple_countries":true,"allows_geo_area":false,"display_order":20},{"code":"multi_country","canonical_name":"Multi-country","requires_country":false,"allows_multiple_countries":true,"allows_geo_area":false,"display_order":30},{"code":"national","canonical_name":"National","requires_country":true,"allows_multiple_countries":false,"allows_geo_area":false,"display_order":40},{"code":"subnational","canonical_name":"Subnational","requires_country":true,"allows_multiple_countries":false,"allows_geo_area":true,"display_order":50},{"code":"local","canonical_name":"Local","requires_country":true,"allows_multiple_countries":false,"allows_geo_area":true,"display_order":60}]'::jsonb) as e(code text, canonical_name text, requires_country boolean, allows_multiple_countries boolean, allows_geo_area boolean, display_order integer) left join public.territorial_scopes t using (code) where t.code is null or t.canonical_name is distinct from e.canonical_name or t.requires_country is distinct from e.requires_country or t.allows_multiple_countries is distinct from e.allows_multiple_countries or t.allows_geo_area is distinct from e.allows_geo_area or t.display_order is distinct from e.display_order or t.is_active is distinct from true) then raise exception '5D-C territorial_scopes payload mismatch'; end if;
  if exists (select 1 from jsonb_to_recordset('[{"code":"association_football_goalkeeper","canonical_name":"Association football goalkeeper","display_order":10},{"code":"association_football_centre_back","canonical_name":"Association football centre-back","display_order":20},{"code":"association_football_full_back","canonical_name":"Association football full-back or wing-back","display_order":30},{"code":"association_football_defensive_midfielder","canonical_name":"Association football defensive midfielder","display_order":40},{"code":"association_football_central_midfielder","canonical_name":"Association football central midfielder","display_order":50},{"code":"association_football_attacking_midfielder","canonical_name":"Association football attacking midfielder","display_order":60},{"code":"association_football_winger","canonical_name":"Association football winger","display_order":70},{"code":"association_football_second_striker","canonical_name":"Association football second striker","display_order":80},{"code":"association_football_centre_forward","canonical_name":"Association football centre-forward","display_order":90},{"code":"eight_a_side_goalkeeper","canonical_name":"Eight-a-side goalkeeper","display_order":10},{"code":"eight_a_side_central_defender","canonical_name":"Eight-a-side central defender","display_order":20},{"code":"eight_a_side_wide_defender","canonical_name":"Eight-a-side wide defender","display_order":30},{"code":"eight_a_side_playmaker","canonical_name":"Eight-a-side playmaker","display_order":40},{"code":"eight_a_side_wide_attacker","canonical_name":"Eight-a-side wide attacker","display_order":50},{"code":"eight_a_side_centre_forward","canonical_name":"Eight-a-side centre-forward","display_order":60},{"code":"futsal_goalkeeper","canonical_name":"Futsal goalkeeper","display_order":10},{"code":"futsal_fixo","canonical_name":"Futsal fixo","display_order":20},{"code":"futsal_winger","canonical_name":"Futsal winger","display_order":30},{"code":"futsal_pivot","canonical_name":"Futsal pivot","display_order":40},{"code":"futsal_universal","canonical_name":"Futsal universal","display_order":50},{"code":"volleyball_setter","canonical_name":"Volleyball setter","display_order":10},{"code":"volleyball_opposite","canonical_name":"Volleyball opposite","display_order":20},{"code":"volleyball_outside_hitter","canonical_name":"Volleyball outside hitter","display_order":30},{"code":"volleyball_middle_blocker","canonical_name":"Volleyball middle blocker","display_order":40},{"code":"volleyball_libero","canonical_name":"Volleyball libero","display_order":50},{"code":"basketball_point_guard","canonical_name":"Basketball point guard","display_order":10},{"code":"basketball_shooting_guard","canonical_name":"Basketball shooting guard","display_order":20},{"code":"basketball_small_forward","canonical_name":"Basketball small forward","display_order":30},{"code":"basketball_power_forward","canonical_name":"Basketball power forward","display_order":40},{"code":"basketball_center","canonical_name":"Basketball center","display_order":50},{"code":"water_polo_goalkeeper","canonical_name":"Water polo goalkeeper","display_order":10},{"code":"water_polo_center_forward","canonical_name":"Water polo center forward","display_order":20},{"code":"water_polo_center_back","canonical_name":"Water polo center back","display_order":30},{"code":"water_polo_driver","canonical_name":"Water polo driver","display_order":40},{"code":"water_polo_wing","canonical_name":"Water polo wing","display_order":50},{"code":"water_polo_point","canonical_name":"Water polo point","display_order":60},{"code":"handball_goalkeeper","canonical_name":"Handball goalkeeper","display_order":10},{"code":"handball_left_wing","canonical_name":"Handball left wing","display_order":20},{"code":"handball_left_back","canonical_name":"Handball left back","display_order":30},{"code":"handball_center_back","canonical_name":"Handball center back","display_order":40},{"code":"handball_right_back","canonical_name":"Handball right back","display_order":50},{"code":"handball_right_wing","canonical_name":"Handball right wing","display_order":60},{"code":"handball_pivot","canonical_name":"Handball pivot","display_order":70},{"code":"rugby_prop","canonical_name":"Rugby prop","display_order":10},{"code":"rugby_hooker","canonical_name":"Rugby hooker","display_order":20},{"code":"rugby_lock","canonical_name":"Rugby lock","display_order":30},{"code":"rugby_flanker","canonical_name":"Rugby flanker","display_order":40},{"code":"rugby_number_eight","canonical_name":"Rugby number eight","display_order":50},{"code":"rugby_scrum_half","canonical_name":"Rugby scrum-half","display_order":60},{"code":"rugby_fly_half","canonical_name":"Rugby fly-half","display_order":70},{"code":"rugby_center","canonical_name":"Rugby center","display_order":80},{"code":"rugby_wing","canonical_name":"Rugby wing","display_order":90},{"code":"rugby_fullback","canonical_name":"Rugby fullback","display_order":100},{"code":"field_hockey_goalkeeper","canonical_name":"Field hockey goalkeeper","display_order":10},{"code":"field_hockey_defender","canonical_name":"Field hockey defender","display_order":20},{"code":"field_hockey_midfielder","canonical_name":"Field hockey midfielder","display_order":30},{"code":"field_hockey_forward","canonical_name":"Field hockey forward","display_order":40},{"code":"ice_hockey_goaltender","canonical_name":"Ice hockey goaltender","display_order":10},{"code":"ice_hockey_defenseman","canonical_name":"Ice hockey defenseman","display_order":20},{"code":"ice_hockey_left_wing","canonical_name":"Ice hockey left wing","display_order":30},{"code":"ice_hockey_center","canonical_name":"Ice hockey center","display_order":40},{"code":"ice_hockey_right_wing","canonical_name":"Ice hockey right wing","display_order":50},{"code":"baseball_pitcher","canonical_name":"Baseball pitcher","display_order":10},{"code":"baseball_catcher","canonical_name":"Baseball catcher","display_order":20},{"code":"baseball_first_base","canonical_name":"Baseball first baseman","display_order":30},{"code":"baseball_second_base","canonical_name":"Baseball second baseman","display_order":40},{"code":"baseball_third_base","canonical_name":"Baseball third baseman","display_order":50},{"code":"baseball_shortstop","canonical_name":"Baseball shortstop","display_order":60},{"code":"baseball_left_fielder","canonical_name":"Baseball left fielder","display_order":70},{"code":"baseball_center_fielder","canonical_name":"Baseball center fielder","display_order":80},{"code":"baseball_right_fielder","canonical_name":"Baseball right fielder","display_order":90},{"code":"baseball_designated_hitter","canonical_name":"Baseball designated hitter","display_order":100},{"code":"softball_pitcher","canonical_name":"Softball pitcher","display_order":10},{"code":"softball_catcher","canonical_name":"Softball catcher","display_order":20},{"code":"softball_first_base","canonical_name":"Softball first baseman","display_order":30},{"code":"softball_second_base","canonical_name":"Softball second baseman","display_order":40},{"code":"softball_third_base","canonical_name":"Softball third baseman","display_order":50},{"code":"softball_shortstop","canonical_name":"Softball shortstop","display_order":60},{"code":"softball_left_fielder","canonical_name":"Softball left fielder","display_order":70},{"code":"softball_center_fielder","canonical_name":"Softball center fielder","display_order":80},{"code":"softball_right_fielder","canonical_name":"Softball right fielder","display_order":90},{"code":"lacrosse_goalkeeper","canonical_name":"Lacrosse goalkeeper","display_order":10},{"code":"lacrosse_defender","canonical_name":"Lacrosse defender","display_order":20},{"code":"lacrosse_midfielder","canonical_name":"Lacrosse midfielder","display_order":30},{"code":"lacrosse_attack","canonical_name":"Lacrosse attack","display_order":40},{"code":"lacrosse_long_stick_midfielder","canonical_name":"Lacrosse long-stick midfielder","display_order":50},{"code":"lacrosse_faceoff_specialist","canonical_name":"Lacrosse faceoff specialist","display_order":60},{"code":"american_football_quarterback","canonical_name":"American football quarterback","display_order":10},{"code":"american_football_running_back","canonical_name":"American football running back","display_order":20},{"code":"american_football_wide_receiver","canonical_name":"American football wide receiver","display_order":30},{"code":"american_football_tight_end","canonical_name":"American football tight end","display_order":40},{"code":"american_football_offensive_lineman","canonical_name":"American football offensive lineman","display_order":50},{"code":"american_football_defensive_lineman","canonical_name":"American football defensive lineman","display_order":60},{"code":"american_football_linebacker","canonical_name":"American football linebacker","display_order":70},{"code":"american_football_cornerback","canonical_name":"American football cornerback","display_order":80},{"code":"american_football_safety","canonical_name":"American football safety","display_order":90},{"code":"american_football_kicker_punter","canonical_name":"American football kicker or punter","display_order":100}]'::jsonb) as e(code text, canonical_name text, display_order integer) left join public.player_positions t using (code) where t.code is null or t.canonical_name is distinct from e.canonical_name or t.display_order is distinct from e.display_order or t.is_active is distinct from true) then raise exception '5D-C player_positions payload mismatch'; end if;
  if exists (select 1 from jsonb_to_recordset('[{"code":"president","canonical_name":"President","display_order":10},{"code":"vice_president","canonical_name":"Vice president","display_order":20},{"code":"sporting_director","canonical_name":"Sporting director","display_order":30},{"code":"general_manager","canonical_name":"General manager","display_order":40},{"code":"secretary","canonical_name":"Secretary","display_order":50},{"code":"team_manager","canonical_name":"Team manager","display_order":60},{"code":"team_official","canonical_name":"Team official","display_order":70},{"code":"head_coach","canonical_name":"Head coach","display_order":80},{"code":"assistant_coach","canonical_name":"Assistant coach","display_order":90},{"code":"technical_assistant","canonical_name":"Technical assistant","display_order":100},{"code":"match_analyst","canonical_name":"Match analyst","display_order":110},{"code":"video_analyst","canonical_name":"Video analyst","display_order":120},{"code":"strength_conditioning_coach","canonical_name":"Strength and conditioning coach","display_order":130},{"code":"goalkeeping_coach","canonical_name":"Goalkeeping coach","display_order":140},{"code":"team_doctor","canonical_name":"Team doctor","display_order":150},{"code":"physiotherapist","canonical_name":"Physiotherapist","display_order":160},{"code":"osteopath","canonical_name":"Osteopath","display_order":170},{"code":"massage_therapist","canonical_name":"Massage therapist","display_order":180},{"code":"mental_performance_coach","canonical_name":"Mental performance coach","display_order":190},{"code":"nutritionist","canonical_name":"Nutritionist","display_order":200},{"code":"scout","canonical_name":"Scout","display_order":210},{"code":"talent_scout","canonical_name":"Talent scout","display_order":220},{"code":"press_officer","canonical_name":"Press officer","display_order":230},{"code":"social_media_manager","canonical_name":"Social media manager","display_order":240},{"code":"photographer","canonical_name":"Photographer","display_order":250},{"code":"content_creator","canonical_name":"Content creator","display_order":260}]'::jsonb) as e(code text, canonical_name text, display_order integer) left join public.staff_roles t using (code) where t.code is null or t.canonical_name is distinct from e.canonical_name or t.display_order is distinct from e.display_order or t.is_active is distinct from true) then raise exception '5D-C staff_roles payload mismatch'; end if;
  if exists (select 1 from jsonb_to_recordset('[{"position_code":"association_football_goalkeeper","sport_code":"football","discipline_code":"association_football","variant_code":"eleven_a_side"},{"position_code":"association_football_centre_back","sport_code":"football","discipline_code":"association_football","variant_code":"eleven_a_side"},{"position_code":"association_football_full_back","sport_code":"football","discipline_code":"association_football","variant_code":"eleven_a_side"},{"position_code":"association_football_defensive_midfielder","sport_code":"football","discipline_code":"association_football","variant_code":"eleven_a_side"},{"position_code":"association_football_central_midfielder","sport_code":"football","discipline_code":"association_football","variant_code":"eleven_a_side"},{"position_code":"association_football_attacking_midfielder","sport_code":"football","discipline_code":"association_football","variant_code":"eleven_a_side"},{"position_code":"association_football_winger","sport_code":"football","discipline_code":"association_football","variant_code":"eleven_a_side"},{"position_code":"association_football_second_striker","sport_code":"football","discipline_code":"association_football","variant_code":"eleven_a_side"},{"position_code":"association_football_centre_forward","sport_code":"football","discipline_code":"association_football","variant_code":"eleven_a_side"},{"position_code":"eight_a_side_goalkeeper","sport_code":"football","discipline_code":"association_football","variant_code":"eight_a_side"},{"position_code":"eight_a_side_central_defender","sport_code":"football","discipline_code":"association_football","variant_code":"eight_a_side"},{"position_code":"eight_a_side_wide_defender","sport_code":"football","discipline_code":"association_football","variant_code":"eight_a_side"},{"position_code":"eight_a_side_playmaker","sport_code":"football","discipline_code":"association_football","variant_code":"eight_a_side"},{"position_code":"eight_a_side_wide_attacker","sport_code":"football","discipline_code":"association_football","variant_code":"eight_a_side"},{"position_code":"eight_a_side_centre_forward","sport_code":"football","discipline_code":"association_football","variant_code":"eight_a_side"},{"position_code":"futsal_goalkeeper","sport_code":"football","discipline_code":"futsal","variant_code":null},{"position_code":"futsal_fixo","sport_code":"football","discipline_code":"futsal","variant_code":null},{"position_code":"futsal_winger","sport_code":"football","discipline_code":"futsal","variant_code":null},{"position_code":"futsal_pivot","sport_code":"football","discipline_code":"futsal","variant_code":null},{"position_code":"futsal_universal","sport_code":"football","discipline_code":"futsal","variant_code":null},{"position_code":"volleyball_setter","sport_code":"volleyball","discipline_code":null,"variant_code":null},{"position_code":"volleyball_opposite","sport_code":"volleyball","discipline_code":null,"variant_code":null},{"position_code":"volleyball_outside_hitter","sport_code":"volleyball","discipline_code":null,"variant_code":null},{"position_code":"volleyball_middle_blocker","sport_code":"volleyball","discipline_code":null,"variant_code":null},{"position_code":"volleyball_libero","sport_code":"volleyball","discipline_code":null,"variant_code":null},{"position_code":"basketball_point_guard","sport_code":"basketball","discipline_code":null,"variant_code":null},{"position_code":"basketball_shooting_guard","sport_code":"basketball","discipline_code":null,"variant_code":null},{"position_code":"basketball_small_forward","sport_code":"basketball","discipline_code":null,"variant_code":null},{"position_code":"basketball_power_forward","sport_code":"basketball","discipline_code":null,"variant_code":null},{"position_code":"basketball_center","sport_code":"basketball","discipline_code":null,"variant_code":null},{"position_code":"water_polo_goalkeeper","sport_code":"water_polo","discipline_code":null,"variant_code":null},{"position_code":"water_polo_center_forward","sport_code":"water_polo","discipline_code":null,"variant_code":null},{"position_code":"water_polo_center_back","sport_code":"water_polo","discipline_code":null,"variant_code":null},{"position_code":"water_polo_driver","sport_code":"water_polo","discipline_code":null,"variant_code":null},{"position_code":"water_polo_wing","sport_code":"water_polo","discipline_code":null,"variant_code":null},{"position_code":"water_polo_point","sport_code":"water_polo","discipline_code":null,"variant_code":null},{"position_code":"handball_goalkeeper","sport_code":"handball","discipline_code":null,"variant_code":null},{"position_code":"handball_left_wing","sport_code":"handball","discipline_code":null,"variant_code":null},{"position_code":"handball_left_back","sport_code":"handball","discipline_code":null,"variant_code":null},{"position_code":"handball_center_back","sport_code":"handball","discipline_code":null,"variant_code":null},{"position_code":"handball_right_back","sport_code":"handball","discipline_code":null,"variant_code":null},{"position_code":"handball_right_wing","sport_code":"handball","discipline_code":null,"variant_code":null},{"position_code":"handball_pivot","sport_code":"handball","discipline_code":null,"variant_code":null},{"position_code":"rugby_prop","sport_code":"rugby","discipline_code":null,"variant_code":null},{"position_code":"rugby_hooker","sport_code":"rugby","discipline_code":null,"variant_code":null},{"position_code":"rugby_lock","sport_code":"rugby","discipline_code":null,"variant_code":null},{"position_code":"rugby_flanker","sport_code":"rugby","discipline_code":null,"variant_code":null},{"position_code":"rugby_number_eight","sport_code":"rugby","discipline_code":null,"variant_code":null},{"position_code":"rugby_scrum_half","sport_code":"rugby","discipline_code":null,"variant_code":null},{"position_code":"rugby_fly_half","sport_code":"rugby","discipline_code":null,"variant_code":null},{"position_code":"rugby_center","sport_code":"rugby","discipline_code":null,"variant_code":null},{"position_code":"rugby_wing","sport_code":"rugby","discipline_code":null,"variant_code":null},{"position_code":"rugby_fullback","sport_code":"rugby","discipline_code":null,"variant_code":null},{"position_code":"field_hockey_goalkeeper","sport_code":"field_hockey","discipline_code":null,"variant_code":null},{"position_code":"field_hockey_defender","sport_code":"field_hockey","discipline_code":null,"variant_code":null},{"position_code":"field_hockey_midfielder","sport_code":"field_hockey","discipline_code":null,"variant_code":null},{"position_code":"field_hockey_forward","sport_code":"field_hockey","discipline_code":null,"variant_code":null},{"position_code":"ice_hockey_goaltender","sport_code":"ice_hockey","discipline_code":null,"variant_code":null},{"position_code":"ice_hockey_defenseman","sport_code":"ice_hockey","discipline_code":null,"variant_code":null},{"position_code":"ice_hockey_left_wing","sport_code":"ice_hockey","discipline_code":null,"variant_code":null},{"position_code":"ice_hockey_center","sport_code":"ice_hockey","discipline_code":null,"variant_code":null},{"position_code":"ice_hockey_right_wing","sport_code":"ice_hockey","discipline_code":null,"variant_code":null},{"position_code":"baseball_pitcher","sport_code":"baseball","discipline_code":null,"variant_code":null},{"position_code":"baseball_catcher","sport_code":"baseball","discipline_code":null,"variant_code":null},{"position_code":"baseball_first_base","sport_code":"baseball","discipline_code":null,"variant_code":null},{"position_code":"baseball_second_base","sport_code":"baseball","discipline_code":null,"variant_code":null},{"position_code":"baseball_third_base","sport_code":"baseball","discipline_code":null,"variant_code":null},{"position_code":"baseball_shortstop","sport_code":"baseball","discipline_code":null,"variant_code":null},{"position_code":"baseball_left_fielder","sport_code":"baseball","discipline_code":null,"variant_code":null},{"position_code":"baseball_center_fielder","sport_code":"baseball","discipline_code":null,"variant_code":null},{"position_code":"baseball_right_fielder","sport_code":"baseball","discipline_code":null,"variant_code":null},{"position_code":"baseball_designated_hitter","sport_code":"baseball","discipline_code":null,"variant_code":null},{"position_code":"softball_pitcher","sport_code":"softball","discipline_code":null,"variant_code":null},{"position_code":"softball_catcher","sport_code":"softball","discipline_code":null,"variant_code":null},{"position_code":"softball_first_base","sport_code":"softball","discipline_code":null,"variant_code":null},{"position_code":"softball_second_base","sport_code":"softball","discipline_code":null,"variant_code":null},{"position_code":"softball_third_base","sport_code":"softball","discipline_code":null,"variant_code":null},{"position_code":"softball_shortstop","sport_code":"softball","discipline_code":null,"variant_code":null},{"position_code":"softball_left_fielder","sport_code":"softball","discipline_code":null,"variant_code":null},{"position_code":"softball_center_fielder","sport_code":"softball","discipline_code":null,"variant_code":null},{"position_code":"softball_right_fielder","sport_code":"softball","discipline_code":null,"variant_code":null},{"position_code":"lacrosse_goalkeeper","sport_code":"lacrosse","discipline_code":null,"variant_code":null},{"position_code":"lacrosse_defender","sport_code":"lacrosse","discipline_code":null,"variant_code":null},{"position_code":"lacrosse_midfielder","sport_code":"lacrosse","discipline_code":null,"variant_code":null},{"position_code":"lacrosse_attack","sport_code":"lacrosse","discipline_code":null,"variant_code":null},{"position_code":"lacrosse_long_stick_midfielder","sport_code":"lacrosse","discipline_code":null,"variant_code":null},{"position_code":"lacrosse_faceoff_specialist","sport_code":"lacrosse","discipline_code":null,"variant_code":null},{"position_code":"american_football_quarterback","sport_code":"american_football","discipline_code":null,"variant_code":null},{"position_code":"american_football_running_back","sport_code":"american_football","discipline_code":null,"variant_code":null},{"position_code":"american_football_wide_receiver","sport_code":"american_football","discipline_code":null,"variant_code":null},{"position_code":"american_football_tight_end","sport_code":"american_football","discipline_code":null,"variant_code":null},{"position_code":"american_football_offensive_lineman","sport_code":"american_football","discipline_code":null,"variant_code":null},{"position_code":"american_football_defensive_lineman","sport_code":"american_football","discipline_code":null,"variant_code":null},{"position_code":"american_football_linebacker","sport_code":"american_football","discipline_code":null,"variant_code":null},{"position_code":"american_football_cornerback","sport_code":"american_football","discipline_code":null,"variant_code":null},{"position_code":"american_football_safety","sport_code":"american_football","discipline_code":null,"variant_code":null},{"position_code":"american_football_kicker_punter","sport_code":"american_football","discipline_code":null,"variant_code":null}]'::jsonb) as e(position_code text, sport_code text, discipline_code text, variant_code text) where not exists (select 1 from public.player_position_applicability a join public.player_positions p on p.id=a.position_id join public.sports s on s.id=a.sport_id left join public.sport_disciplines d on d.id=a.discipline_id left join public.sport_variants v on v.id=a.variant_id where p.code=e.position_code and s.code=e.sport_code and d.code is not distinct from e.discipline_code and v.code is not distinct from e.variant_code and a.is_active=true)) then raise exception '5D-C player applicability payload mismatch'; end if;
  if exists (select 1 from jsonb_to_recordset('[{"source_value":"Portiere","normalized_source_value":"portiere","sport_code":"football","discipline_code":"association_football","variant_code":"eleven_a_side","position_code":"association_football_goalkeeper"},{"source_value":"Difensore centrale","normalized_source_value":"difensore_centrale","sport_code":"football","discipline_code":"association_football","variant_code":"eleven_a_side","position_code":"association_football_centre_back"},{"source_value":"Terzino/Esterno difensivo","normalized_source_value":"terzino_esterno_difensivo","sport_code":"football","discipline_code":"association_football","variant_code":"eleven_a_side","position_code":"association_football_full_back"},{"source_value":"Mediano","normalized_source_value":"mediano","sport_code":"football","discipline_code":"association_football","variant_code":"eleven_a_side","position_code":"association_football_defensive_midfielder"},{"source_value":"Centrocampista centrale","normalized_source_value":"centrocampista_centrale","sport_code":"football","discipline_code":"association_football","variant_code":"eleven_a_side","position_code":"association_football_central_midfielder"},{"source_value":"Trequartista","normalized_source_value":"trequartista","sport_code":"football","discipline_code":"association_football","variant_code":"eleven_a_side","position_code":"association_football_attacking_midfielder"},{"source_value":"Esterno offensivo/Ala","normalized_source_value":"esterno_offensivo_ala","sport_code":"football","discipline_code":"association_football","variant_code":"eleven_a_side","position_code":"association_football_winger"},{"source_value":"Seconda punta","normalized_source_value":"seconda_punta","sport_code":"football","discipline_code":"association_football","variant_code":"eleven_a_side","position_code":"association_football_second_striker"},{"source_value":"Punta centrale","normalized_source_value":"punta_centrale","sport_code":"football","discipline_code":"association_football","variant_code":"eleven_a_side","position_code":"association_football_centre_forward"},{"source_value":"Portiere","normalized_source_value":"portiere","sport_code":"football","discipline_code":"association_football","variant_code":"eight_a_side","position_code":"eight_a_side_goalkeeper"},{"source_value":"Difensore Centrale","normalized_source_value":"difensore_centrale","sport_code":"football","discipline_code":"association_football","variant_code":"eight_a_side","position_code":"eight_a_side_central_defender"},{"source_value":"Esterno Basso","normalized_source_value":"esterno_basso","sport_code":"football","discipline_code":"association_football","variant_code":"eight_a_side","position_code":"eight_a_side_wide_defender"},{"source_value":"Regista","normalized_source_value":"regista","sport_code":"football","discipline_code":"association_football","variant_code":"eight_a_side","position_code":"eight_a_side_playmaker"},{"source_value":"Esterno Alto","normalized_source_value":"esterno_alto","sport_code":"football","discipline_code":"association_football","variant_code":"eight_a_side","position_code":"eight_a_side_wide_attacker"},{"source_value":"Punta Centrale","normalized_source_value":"punta_centrale","sport_code":"football","discipline_code":"association_football","variant_code":"eight_a_side","position_code":"eight_a_side_centre_forward"},{"source_value":"Portiere","normalized_source_value":"portiere","sport_code":"football","discipline_code":"futsal","variant_code":null,"position_code":"futsal_goalkeeper"},{"source_value":"Fixo","normalized_source_value":"fixo","sport_code":"football","discipline_code":"futsal","variant_code":null,"position_code":"futsal_fixo"},{"source_value":"Ala","normalized_source_value":"ala","sport_code":"football","discipline_code":"futsal","variant_code":null,"position_code":"futsal_winger"},{"source_value":"Pivot","normalized_source_value":"pivot","sport_code":"football","discipline_code":"futsal","variant_code":null,"position_code":"futsal_pivot"},{"source_value":"Universale","normalized_source_value":"universale","sport_code":"football","discipline_code":"futsal","variant_code":null,"position_code":"futsal_universal"},{"source_value":"Palleggiatore","normalized_source_value":"palleggiatore","sport_code":"volleyball","discipline_code":null,"variant_code":null,"position_code":"volleyball_setter"},{"source_value":"Opposto","normalized_source_value":"opposto","sport_code":"volleyball","discipline_code":null,"variant_code":null,"position_code":"volleyball_opposite"},{"source_value":"Schiacciatore","normalized_source_value":"schiacciatore","sport_code":"volleyball","discipline_code":null,"variant_code":null,"position_code":"volleyball_outside_hitter"},{"source_value":"Centrale","normalized_source_value":"centrale","sport_code":"volleyball","discipline_code":null,"variant_code":null,"position_code":"volleyball_middle_blocker"},{"source_value":"Libero","normalized_source_value":"libero","sport_code":"volleyball","discipline_code":null,"variant_code":null,"position_code":"volleyball_libero"},{"source_value":"Playmaker (PG)","normalized_source_value":"playmaker_pg","sport_code":"basketball","discipline_code":null,"variant_code":null,"position_code":"basketball_point_guard"},{"source_value":"Guardia (SG)","normalized_source_value":"guardia_sg","sport_code":"basketball","discipline_code":null,"variant_code":null,"position_code":"basketball_shooting_guard"},{"source_value":"Ala piccola (SF)","normalized_source_value":"ala_piccola_sf","sport_code":"basketball","discipline_code":null,"variant_code":null,"position_code":"basketball_small_forward"},{"source_value":"Ala grande (PF)","normalized_source_value":"ala_grande_pf","sport_code":"basketball","discipline_code":null,"variant_code":null,"position_code":"basketball_power_forward"},{"source_value":"Centro (C)","normalized_source_value":"centro_c","sport_code":"basketball","discipline_code":null,"variant_code":null,"position_code":"basketball_center"},{"source_value":"Portiere","normalized_source_value":"portiere","sport_code":"water_polo","discipline_code":null,"variant_code":null,"position_code":"water_polo_goalkeeper"},{"source_value":"Centroboa","normalized_source_value":"centroboa","sport_code":"water_polo","discipline_code":null,"variant_code":null,"position_code":"water_polo_center_forward"},{"source_value":"Marcatore (Hole-D)","normalized_source_value":"marcatore_hole_d","sport_code":"water_polo","discipline_code":null,"variant_code":null,"position_code":"water_polo_center_back"},{"source_value":"Driver/Perimetrale","normalized_source_value":"driver_perimetrale","sport_code":"water_polo","discipline_code":null,"variant_code":null,"position_code":"water_polo_driver"},{"source_value":"Ala","normalized_source_value":"ala","sport_code":"water_polo","discipline_code":null,"variant_code":null,"position_code":"water_polo_wing"},{"source_value":"Punto/Regista","normalized_source_value":"punto_regista","sport_code":"water_polo","discipline_code":null,"variant_code":null,"position_code":"water_polo_point"},{"source_value":"Portiere","normalized_source_value":"portiere","sport_code":"handball","discipline_code":null,"variant_code":null,"position_code":"handball_goalkeeper"},{"source_value":"Ala sinistra","normalized_source_value":"ala_sinistra","sport_code":"handball","discipline_code":null,"variant_code":null,"position_code":"handball_left_wing"},{"source_value":"Terzino sinistro","normalized_source_value":"terzino_sinistro","sport_code":"handball","discipline_code":null,"variant_code":null,"position_code":"handball_left_back"},{"source_value":"Centrale","normalized_source_value":"centrale","sport_code":"handball","discipline_code":null,"variant_code":null,"position_code":"handball_center_back"},{"source_value":"Terzino destro","normalized_source_value":"terzino_destro","sport_code":"handball","discipline_code":null,"variant_code":null,"position_code":"handball_right_back"},{"source_value":"Ala destra","normalized_source_value":"ala_destra","sport_code":"handball","discipline_code":null,"variant_code":null,"position_code":"handball_right_wing"},{"source_value":"Pivot","normalized_source_value":"pivot","sport_code":"handball","discipline_code":null,"variant_code":null,"position_code":"handball_pivot"},{"source_value":"Pilone","normalized_source_value":"pilone","sport_code":"rugby","discipline_code":null,"variant_code":null,"position_code":"rugby_prop"},{"source_value":"Tallonatore","normalized_source_value":"tallonatore","sport_code":"rugby","discipline_code":null,"variant_code":null,"position_code":"rugby_hooker"},{"source_value":"Seconda linea","normalized_source_value":"seconda_linea","sport_code":"rugby","discipline_code":null,"variant_code":null,"position_code":"rugby_lock"},{"source_value":"Flanker","normalized_source_value":"flanker","sport_code":"rugby","discipline_code":null,"variant_code":null,"position_code":"rugby_flanker"},{"source_value":"Numero 8","normalized_source_value":"numero_8","sport_code":"rugby","discipline_code":null,"variant_code":null,"position_code":"rugby_number_eight"},{"source_value":"Mediano di mischia","normalized_source_value":"mediano_di_mischia","sport_code":"rugby","discipline_code":null,"variant_code":null,"position_code":"rugby_scrum_half"},{"source_value":"Apertura","normalized_source_value":"apertura","sport_code":"rugby","discipline_code":null,"variant_code":null,"position_code":"rugby_fly_half"},{"source_value":"Centro","normalized_source_value":"centro","sport_code":"rugby","discipline_code":null,"variant_code":null,"position_code":"rugby_center"},{"source_value":"Ala","normalized_source_value":"ala","sport_code":"rugby","discipline_code":null,"variant_code":null,"position_code":"rugby_wing"},{"source_value":"Estremo","normalized_source_value":"estremo","sport_code":"rugby","discipline_code":null,"variant_code":null,"position_code":"rugby_fullback"},{"source_value":"Portiere","normalized_source_value":"portiere","sport_code":"field_hockey","discipline_code":null,"variant_code":null,"position_code":"field_hockey_goalkeeper"},{"source_value":"Difensore","normalized_source_value":"difensore","sport_code":"field_hockey","discipline_code":null,"variant_code":null,"position_code":"field_hockey_defender"},{"source_value":"Centrocampista","normalized_source_value":"centrocampista","sport_code":"field_hockey","discipline_code":null,"variant_code":null,"position_code":"field_hockey_midfielder"},{"source_value":"Attaccante","normalized_source_value":"attaccante","sport_code":"field_hockey","discipline_code":null,"variant_code":null,"position_code":"field_hockey_forward"},{"source_value":"Portiere","normalized_source_value":"portiere","sport_code":"ice_hockey","discipline_code":null,"variant_code":null,"position_code":"ice_hockey_goaltender"},{"source_value":"Difensore","normalized_source_value":"difensore","sport_code":"ice_hockey","discipline_code":null,"variant_code":null,"position_code":"ice_hockey_defenseman"},{"source_value":"Ala sinistra","normalized_source_value":"ala_sinistra","sport_code":"ice_hockey","discipline_code":null,"variant_code":null,"position_code":"ice_hockey_left_wing"},{"source_value":"Centro","normalized_source_value":"centro","sport_code":"ice_hockey","discipline_code":null,"variant_code":null,"position_code":"ice_hockey_center"},{"source_value":"Ala destra","normalized_source_value":"ala_destra","sport_code":"ice_hockey","discipline_code":null,"variant_code":null,"position_code":"ice_hockey_right_wing"},{"source_value":"Pitcher","normalized_source_value":"pitcher","sport_code":"baseball","discipline_code":null,"variant_code":null,"position_code":"baseball_pitcher"},{"source_value":"Catcher","normalized_source_value":"catcher","sport_code":"baseball","discipline_code":null,"variant_code":null,"position_code":"baseball_catcher"},{"source_value":"Prima base","normalized_source_value":"prima_base","sport_code":"baseball","discipline_code":null,"variant_code":null,"position_code":"baseball_first_base"},{"source_value":"Seconda base","normalized_source_value":"seconda_base","sport_code":"baseball","discipline_code":null,"variant_code":null,"position_code":"baseball_second_base"},{"source_value":"Terza base","normalized_source_value":"terza_base","sport_code":"baseball","discipline_code":null,"variant_code":null,"position_code":"baseball_third_base"},{"source_value":"Interbase","normalized_source_value":"interbase","sport_code":"baseball","discipline_code":null,"variant_code":null,"position_code":"baseball_shortstop"},{"source_value":"Esterno sinistro","normalized_source_value":"esterno_sinistro","sport_code":"baseball","discipline_code":null,"variant_code":null,"position_code":"baseball_left_fielder"},{"source_value":"Esterno centro","normalized_source_value":"esterno_centro","sport_code":"baseball","discipline_code":null,"variant_code":null,"position_code":"baseball_center_fielder"},{"source_value":"Esterno destro","normalized_source_value":"esterno_destro","sport_code":"baseball","discipline_code":null,"variant_code":null,"position_code":"baseball_right_fielder"},{"source_value":"Battitore designato","normalized_source_value":"battitore_designato","sport_code":"baseball","discipline_code":null,"variant_code":null,"position_code":"baseball_designated_hitter"},{"source_value":"Pitcher","normalized_source_value":"pitcher","sport_code":"softball","discipline_code":null,"variant_code":null,"position_code":"softball_pitcher"},{"source_value":"Catcher","normalized_source_value":"catcher","sport_code":"softball","discipline_code":null,"variant_code":null,"position_code":"softball_catcher"},{"source_value":"Prima base","normalized_source_value":"prima_base","sport_code":"softball","discipline_code":null,"variant_code":null,"position_code":"softball_first_base"},{"source_value":"Seconda base","normalized_source_value":"seconda_base","sport_code":"softball","discipline_code":null,"variant_code":null,"position_code":"softball_second_base"},{"source_value":"Terza base","normalized_source_value":"terza_base","sport_code":"softball","discipline_code":null,"variant_code":null,"position_code":"softball_third_base"},{"source_value":"Interbase","normalized_source_value":"interbase","sport_code":"softball","discipline_code":null,"variant_code":null,"position_code":"softball_shortstop"},{"source_value":"Esterno sinistro","normalized_source_value":"esterno_sinistro","sport_code":"softball","discipline_code":null,"variant_code":null,"position_code":"softball_left_fielder"},{"source_value":"Esterno centro","normalized_source_value":"esterno_centro","sport_code":"softball","discipline_code":null,"variant_code":null,"position_code":"softball_center_fielder"},{"source_value":"Esterno destro","normalized_source_value":"esterno_destro","sport_code":"softball","discipline_code":null,"variant_code":null,"position_code":"softball_right_fielder"},{"source_value":"Portiere","normalized_source_value":"portiere","sport_code":"lacrosse","discipline_code":null,"variant_code":null,"position_code":"lacrosse_goalkeeper"},{"source_value":"Difensore","normalized_source_value":"difensore","sport_code":"lacrosse","discipline_code":null,"variant_code":null,"position_code":"lacrosse_defender"},{"source_value":"Centrocampista","normalized_source_value":"centrocampista","sport_code":"lacrosse","discipline_code":null,"variant_code":null,"position_code":"lacrosse_midfielder"},{"source_value":"Attaccante","normalized_source_value":"attaccante","sport_code":"lacrosse","discipline_code":null,"variant_code":null,"position_code":"lacrosse_attack"},{"source_value":"LSM","normalized_source_value":"lsm","sport_code":"lacrosse","discipline_code":null,"variant_code":null,"position_code":"lacrosse_long_stick_midfielder"},{"source_value":"Faceoff specialist","normalized_source_value":"faceoff_specialist","sport_code":"lacrosse","discipline_code":null,"variant_code":null,"position_code":"lacrosse_faceoff_specialist"},{"source_value":"Quarterback","normalized_source_value":"quarterback","sport_code":"american_football","discipline_code":null,"variant_code":null,"position_code":"american_football_quarterback"},{"source_value":"Running back","normalized_source_value":"running_back","sport_code":"american_football","discipline_code":null,"variant_code":null,"position_code":"american_football_running_back"},{"source_value":"Wide receiver","normalized_source_value":"wide_receiver","sport_code":"american_football","discipline_code":null,"variant_code":null,"position_code":"american_football_wide_receiver"},{"source_value":"Tight end","normalized_source_value":"tight_end","sport_code":"american_football","discipline_code":null,"variant_code":null,"position_code":"american_football_tight_end"},{"source_value":"Offensive lineman","normalized_source_value":"offensive_lineman","sport_code":"american_football","discipline_code":null,"variant_code":null,"position_code":"american_football_offensive_lineman"},{"source_value":"Defensive lineman","normalized_source_value":"defensive_lineman","sport_code":"american_football","discipline_code":null,"variant_code":null,"position_code":"american_football_defensive_lineman"},{"source_value":"Linebacker","normalized_source_value":"linebacker","sport_code":"american_football","discipline_code":null,"variant_code":null,"position_code":"american_football_linebacker"},{"source_value":"Cornerback","normalized_source_value":"cornerback","sport_code":"american_football","discipline_code":null,"variant_code":null,"position_code":"american_football_cornerback"},{"source_value":"Safety","normalized_source_value":"safety","sport_code":"american_football","discipline_code":null,"variant_code":null,"position_code":"american_football_safety"},{"source_value":"Kicker/Punter","normalized_source_value":"kicker_punter","sport_code":"american_football","discipline_code":null,"variant_code":null,"position_code":"american_football_kicker_punter"}]'::jsonb) as e(source_value text, normalized_source_value text, sport_code text, discipline_code text, variant_code text, position_code text) where not exists (select 1 from public.legacy_player_position_mappings m join public.player_positions p on p.id=m.position_id join public.sports s on s.id=m.sport_id left join public.sport_disciplines d on d.id=m.discipline_id left join public.sport_variants v on v.id=m.variant_id where m.source_value=e.source_value and m.normalized_source_value=e.normalized_source_value and s.code=e.sport_code and d.code is not distinct from e.discipline_code and v.code is not distinct from e.variant_code and p.code=e.position_code and m.is_active=true)) then raise exception '5D-C player legacy mapping payload mismatch'; end if;
  if exists (select 1 from jsonb_to_recordset('[{"source_value":"Presidente","normalized_source_value":"presidente","staff_role_code":"president"},{"source_value":"Vicepresidente","normalized_source_value":"vicepresidente","staff_role_code":"vice_president"},{"source_value":"Direttore Sportivo","normalized_source_value":"direttore_sportivo","staff_role_code":"sporting_director"},{"source_value":"Direttore Generale","normalized_source_value":"direttore_generale","staff_role_code":"general_manager"},{"source_value":"Segretario","normalized_source_value":"segretario","staff_role_code":"secretary"},{"source_value":"Team manager","normalized_source_value":"team_manager","staff_role_code":"team_manager"},{"source_value":"Dirigente Accompagnatore","normalized_source_value":"dirigente_accompagnatore","staff_role_code":"team_official"},{"source_value":"Allenatore","normalized_source_value":"allenatore","staff_role_code":"head_coach"},{"source_value":"Vice Allenatore","normalized_source_value":"vice_allenatore","staff_role_code":"assistant_coach"},{"source_value":"Collaboratore Tecnico","normalized_source_value":"collaboratore_tecnico","staff_role_code":"technical_assistant"},{"source_value":"Match Analyst","normalized_source_value":"match_analyst","staff_role_code":"match_analyst"},{"source_value":"Video Analyst","normalized_source_value":"video_analyst","staff_role_code":"video_analyst"},{"source_value":"Preparatore Atletico","normalized_source_value":"preparatore_atletico","staff_role_code":"strength_conditioning_coach"},{"source_value":"Preparatore Portieri","normalized_source_value":"preparatore_portieri","staff_role_code":"goalkeeping_coach"},{"source_value":"Medico Sociale","normalized_source_value":"medico_sociale","staff_role_code":"team_doctor"},{"source_value":"Fisioterapista","normalized_source_value":"fisioterapista","staff_role_code":"physiotherapist"},{"source_value":"Osteopata","normalized_source_value":"osteopata","staff_role_code":"osteopath"},{"source_value":"Massaggiatore","normalized_source_value":"massaggiatore","staff_role_code":"massage_therapist"},{"source_value":"Mental Coach","normalized_source_value":"mental_coach","staff_role_code":"mental_performance_coach"},{"source_value":"Nutrizionista","normalized_source_value":"nutrizionista","staff_role_code":"nutritionist"},{"source_value":"Scout","normalized_source_value":"scout","staff_role_code":"scout"},{"source_value":"Talent Scout","normalized_source_value":"talent_scout","staff_role_code":"talent_scout"},{"source_value":"Addetto Stampa","normalized_source_value":"addetto_stampa","staff_role_code":"press_officer"},{"source_value":"Social Media Manager","normalized_source_value":"social_media_manager","staff_role_code":"social_media_manager"},{"source_value":"Fotografo","normalized_source_value":"fotografo","staff_role_code":"photographer"},{"source_value":"Content Creator","normalized_source_value":"content_creator","staff_role_code":"content_creator"}]'::jsonb) as e(source_value text, normalized_source_value text, staff_role_code text) where not exists (select 1 from public.legacy_staff_role_mappings m join public.staff_roles r on r.id=m.staff_role_id where m.source_value=e.source_value and m.normalized_source_value=e.normalized_source_value and r.code=e.staff_role_code and m.is_active=true)) then raise exception '5D-C staff legacy mapping payload mismatch'; end if;
end
$$;

commit;
