begin;

-- Closed, product-authorized catalogues from section 5 of the five country briefs.
-- Existing records are updated in place so UUIDs and historical references survive.

-- Minimal canonical vocabulary required by the selected combinations.
insert into public.sports(code,canonical_name,is_active,display_order) values
  ('floorball','Floorball',true,130), ('skiing','Skiing',true,140),
  ('biathlon','Biathlon',true,150), ('tennis','Tennis',true,160)
on conflict(code) do update set canonical_name=excluded.canonical_name,is_active=true,display_order=excluded.display_order,updated_at=now();

insert into public.sport_variants(discipline_id,code,canonical_name,team_size,is_active,display_order)
select d.id,v.code,v.name,v.team_size,true,v.ord from public.sport_disciplines d
join public.sports s on s.id=d.sport_id and s.code='football'
cross join (values ('six_a_side','6-a-side',6,30),('seven_a_side','7-a-side',7,40)) v(code,name,team_size,ord)
where d.code='association_football'
on conflict(discipline_id,code) do update set canonical_name=excluded.canonical_name,team_size=excluded.team_size,is_active=true,display_order=excluded.display_order,updated_at=now();

with mappings(source_value,normalized_source_value,sport_code,discipline_code,variant_code,label) as (values
 ('Calcio a 6','calcio_a_6','football','association_football','six_a_side','Calcio a 6'),
 ('Calcio a 7','calcio_a_7','football','association_football','seven_a_side','Calcio a 7'),
 ('Floorball','floorball','floorball',null,null,'Floorball'),
 ('Unihockey','unihockey','floorball',null,null,'Floorball'),
 ('Sci','sci','skiing',null,null,'Sci'), ('Biathlon','biathlon','biathlon',null,null,'Biathlon'),
 ('Tennis','tennis','tennis',null,null,'Tennis')
), resolved as (select m.*,s.id sport_id,d.id discipline_id,v.id variant_id from mappings m join public.sports s on s.code=m.sport_code left join public.sport_disciplines d on d.sport_id=s.id and d.code=m.discipline_code left join public.sport_variants v on v.discipline_id=d.id and v.code=m.variant_code)
insert into public.legacy_sport_mappings(source_value,normalized_source_value,sport_id,discipline_id,variant_id,legacy_display_label,is_active,notes)
select source_value,normalized_source_value,sport_id,discipline_id,variant_id,label,true,'Five-country authorized catalogue' from resolved
on conflict(normalized_source_value) do update set sport_id=excluded.sport_id,discipline_id=excluded.discipline_id,variant_id=excluded.variant_id,legacy_display_label=excluded.legacy_display_label,is_active=true,notes=excluded.notes;

with seed(iso2,code,name,ord) as (values
  ('FR','fr_fff','FFF',1)
 ,('FR','fr_ffvolley','FFvolley',2)
 ,('FR','fr_ffbb','FFBB',3)
 ,('FR','fr_ffhandball','FFHandball',4)
 ,('FR','fr_ffr','FFR',5)
 ,('FR','fr_ffhg','FFHG',6)
 ,('FR','fr_ffn','FFN',7)
 ,('FR','fr_ffh','FFH',8)
 ,('FR','fr_ffbs','FFBS',9)
 ,('FR','fr_fffa','FFFA',10)
 ,('FR','fr_france_lacrosse','France Lacrosse',11)
 ,('ES','es_rfef','RFEF',12)
 ,('ES','es_feb','FEB',13)
 ,('ES','es_rfebm','RFEBM',14)
 ,('ES','es_rfer','RFER',15)
 ,('ES','es_rfevb','RFEVB',16)
 ,('ES','es_rfedh','RFEDH',17)
 ,('ES','es_rfen','RFEN',18)
 ,('ES','es_rfeh','RFEH',19)
 ,('ES','es_rfebs','RFEBS',20)
 ,('ES','es_fefa','FEFA',21)
 ,('ES','es_ael','AEL',22)
 ,('CH','ch_asf_sfv','ASF-SFV',23)
 ,('CH','ch_sihf','SIHF',24)
 ,('CH','ch_swiss_unihockey','swiss unihockey',25)
 ,('CH','ch_swiss_basketball','Swiss Basketball',26)
 ,('CH','ch_shv_fsh','SHV-FSH',27)
 ,('CH','ch_swiss_volley','Swiss Volley',28)
 ,('CH','ch_swiss_ski','Swiss-Ski',29)
 ,('CH','ch_swiss_tennis','Swiss Tennis',30)
 ,('CH','ch_fsr','FSR',31)
 ,('CH','ch_sffs','SFFS',32)
 ,('SI','si_nzs','NZS',33)
 ,('SI','si_smz','SMZ',34)
 ,('SI','si_kzs','KZS',35)
 ,('SI','si_organizzatori_locali','Organizzatori locali',36)
 ,('SI','si_rzs','RZS',37)
 ,('SI','si_ozs','OZS',38)
 ,('SI','si_zvds','ZVDS',39)
 ,('SI','si_zhts','ZHTS',40)
 ,('SI','si_zbss','ZBSS',41)
 ,('SI','si_zans','ZANS',42)
 ,('SI','si_rzs_rugby','RZS-Rugby',43)
 ,('SI','si_slovenia_lacrosse','Slovenia Lacrosse',44)
 ,('PL','pl_pzpn','PZPN',45)
 ,('PL','pl_playarena_socca_poland','Playarena / Socca Poland',46)
 ,('PL','pl_pzkosz','PZKosz',47)
 ,('PL','pl_zprp','ZPRP',48)
 ,('PL','pl_pzps','PZPS',49)
 ,('PL','pl_pzhl','PZHL',50)
 ,('PL','pl_pzp','PZP',51)
 ,('PL','pl_pzht','PZHT',52)
 ,('PL','pl_pzbis','PZBiS',53)
 ,('PL','pl_zfap','ZFAP',54)
 ,('PL','pl_pzr','PZR',55)
 ,('PL','pl_pfl','PFL',56)
), resolved as (select seed.*,c.id country_id from seed join public.countries c on c.iso2=seed.iso2)
insert into public.sports_organizations(id,code,canonical_name,organization_type,primary_country_id,provider,source_record_id,source_version,source_metadata,is_active,display_order)
select md5('five-country-org:'||iso2||':'||code)::uuid,code,name,'federation',country_id,'clubandplayer_authorized_catalog',iso2||':organization:'||code,'2026-09-15.five-country','{"evidence":"section_5_closed_list"}',true,ord from resolved
on conflict(provider,source_record_id) do update set code=excluded.code,canonical_name=excluded.canonical_name,primary_country_id=excluded.primary_country_id,is_active=true,display_order=excluded.display_order,updated_at=now();

-- Retire only superseded selectable French catalogue rows; references remain intact.
update public.sports_organization_categories c set is_active=false,updated_at=now()
from public.countries country where c.country_id=country.id and country.iso2='FR'
  and c.provider='clubandplayer_authorized_catalog';

with seed(iso2,sport_key,org_code,code,name,ord) as (values
  ('FR','calcio','fr_fff','national_2','National 2',1)
 ,('FR','calcio','fr_fff','national_3','National 3',2)
 ,('FR','calcio','fr_fff','regional_1_r1','Régional 1 (R1)',3)
 ,('FR','calcio','fr_fff','regional_2_r2','Régional 2 (R2)',4)
 ,('FR','calcio','fr_fff','regional_3_r3','Régional 3 (R3)',5)
 ,('FR','calcio','fr_fff','district_1_d1','District 1 (D1)',6)
 ,('FR','calcio','fr_fff','district_2_d2_et_niveaux_inferieurs','District 2 (D2) et niveaux inférieurs',7)
 ,('FR','calcio','fr_fff','giovanili','Giovanili',8)
 ,('FR','calcio_a_8','fr_fff','pratique_territoriale','Pratique territoriale',1)
 ,('FR','futsal','fr_fff','d2_futsal','D2 Futsal',1)
 ,('FR','futsal','fr_fff','competition_nationale_feminine_de_futsal','Compétition nationale féminine de futsal',2)
 ,('FR','futsal','fr_fff','regional_futsal','Régional Futsal',3)
 ,('FR','futsal','fr_fff','district_futsal','District Futsal',4)
 ,('FR','pallavolo','fr_ffvolley','nationale_2_masculine','Nationale 2 Masculine',1)
 ,('FR','pallavolo','fr_ffvolley','nationale_2_feminine','Nationale 2 Féminine',2)
 ,('FR','pallavolo','fr_ffvolley','nationale_3_masculine','Nationale 3 Masculine',3)
 ,('FR','pallavolo','fr_ffvolley','nationale_3_feminine','Nationale 3 Féminine',4)
 ,('FR','pallavolo','fr_ffvolley','pre_nationale','Pré-Nationale',5)
 ,('FR','pallavolo','fr_ffvolley','regionale','Régionale',6)
 ,('FR','pallavolo','fr_ffvolley','departementale','Départementale',7)
 ,('FR','pallacanestro','fr_ffbb','nationale_masculine_2_nm2','Nationale Masculine 2 (NM2)',1)
 ,('FR','pallacanestro','fr_ffbb','nationale_masculine_3_nm3','Nationale Masculine 3 (NM3)',2)
 ,('FR','pallacanestro','fr_ffbb','nationale_feminine_1_nf1','Nationale Féminine 1 (NF1)',3)
 ,('FR','pallacanestro','fr_ffbb','nationale_feminine_2_nf2','Nationale Féminine 2 (NF2)',4)
 ,('FR','pallacanestro','fr_ffbb','nationale_feminine_3_nf3','Nationale Féminine 3 (NF3)',5)
 ,('FR','pallacanestro','fr_ffbb','regionale_1','Régionale 1',6)
 ,('FR','pallacanestro','fr_ffbb','regionale_2','Régionale 2',7)
 ,('FR','pallacanestro','fr_ffbb','regionale_3','Régionale 3',8)
 ,('FR','pallacanestro','fr_ffbb','pre_regionale','Pré-Régionale',9)
 ,('FR','pallacanestro','fr_ffbb','departementale','Départementale',10)
 ,('FR','pallamano','fr_ffhandball','nationale_2_masculine_n2m','Nationale 2 Masculine (N2M)',1)
 ,('FR','pallamano','fr_ffhandball','nationale_3_masculine_n3m','Nationale 3 Masculine (N3M)',2)
 ,('FR','pallamano','fr_ffhandball','nationale_1_feminine_n1f','Nationale 1 Féminine (N1F)',3)
 ,('FR','pallamano','fr_ffhandball','nationale_2_feminine_n2f','Nationale 2 Féminine (N2F)',4)
 ,('FR','pallamano','fr_ffhandball','nationale_3_feminine_n3f','Nationale 3 Féminine (N3F)',5)
 ,('FR','pallamano','fr_ffhandball','prenationale','Prénationale',6)
 ,('FR','pallamano','fr_ffhandball','regionale','Régionale',7)
 ,('FR','pallamano','fr_ffhandball','departementale','Départementale',8)
 ,('FR','rugby','fr_ffr','federale_1','Fédérale 1',1)
 ,('FR','rugby','fr_ffr','federale_2','Fédérale 2',2)
 ,('FR','rugby','fr_ffr','federale_3','Fédérale 3',3)
 ,('FR','rugby','fr_ffr','elite_1_feminine','Élite 1 Féminine',4)
 ,('FR','rugby','fr_ffr','elite_2_feminine','Élite 2 Féminine',5)
 ,('FR','rugby','fr_ffr','federale_1_feminine','Fédérale 1 Féminine',6)
 ,('FR','rugby','fr_ffr','federale_2_feminine','Fédérale 2 Féminine',7)
 ,('FR','rugby','fr_ffr','regionale_1','Régionale 1',8)
 ,('FR','rugby','fr_ffr','regionale_2','Régionale 2',9)
 ,('FR','rugby','fr_ffr','regionale_3','Régionale 3',10)
 ,('FR','hockey_su_ghiaccio','fr_ffhg','division_2','Division 2',1)
 ,('FR','hockey_su_ghiaccio','fr_ffhg','division_3','Division 3',2)
 ,('FR','hockey_su_ghiaccio','fr_ffhg','championnat_feminin','Championnat Féminin',3)
 ,('FR','hockey_su_ghiaccio','fr_ffhg','giovanili','Giovanili',4)
 ,('FR','pallanuoto','fr_ffn','nationale_1','Nationale 1',1)
 ,('FR','pallanuoto','fr_ffn','nationale_2','Nationale 2',2)
 ,('FR','pallanuoto','fr_ffn','nationale_3','Nationale 3',3)
 ,('FR','pallanuoto','fr_ffn','regionale','Régionale',4)
 ,('FR','hockey_su_prato','fr_ffh','elite_masculine','Elite Masculine',1)
 ,('FR','hockey_su_prato','fr_ffh','elite_feminine','Elite Féminine',2)
 ,('FR','hockey_su_prato','fr_ffh','nationale_1','Nationale 1',3)
 ,('FR','hockey_su_prato','fr_ffh','nationale_2','Nationale 2',4)
 ,('FR','baseball','fr_ffbs','division_1_baseball','Division 1 (Baseball)',1)
 ,('FR','baseball','fr_ffbs','division_2_baseball','Division 2 (Baseball)',2)
 ,('FR','baseball','fr_ffbs','nationale_1_baseball','Nationale 1 (Baseball)',3)
 ,('FR','baseball','fr_ffbs','regionale','Régionale',4)
 ,('FR','softball','fr_ffbs','division_1_softball','Division 1 (Softball)',1)
 ,('FR','softball','fr_ffbs','regionale','Régionale',2)
 ,('FR','football_americano','fr_fffa','division_1_casque_de_diamant','Division 1 (Casque de Diamant)',1)
 ,('FR','football_americano','fr_fffa','division_2_casque_d_or','Division 2 (Casque d''Or)',2)
 ,('FR','football_americano','fr_fffa','division_3_casque_d_argent','Division 3 (Casque d''Argent)',3)
 ,('FR','football_americano','fr_fffa','regionale','Régionale',4)
 ,('FR','lacrosse','fr_france_lacrosse','championnat_de_france_de_lacrosse','Championnat de France de Lacrosse',1)
 ,('ES','calcio','es_rfef','tercera_federacion','Tercera Federación',1)
 ,('ES','calcio','es_rfef','division_de_honor_autonomica','División de Honor Autonómica',2)
 ,('ES','calcio','es_rfef','regional_preferente','Regional Preferente',3)
 ,('ES','calcio','es_rfef','primera_regional','Primera Regional',4)
 ,('ES','calcio','es_rfef','segunda_regional','Segunda Regional',5)
 ,('ES','calcio','es_rfef','tercera_regional','Tercera Regional',6)
 ,('ES','calcio','es_rfef','segunda_federacion_femenina','Segunda Federación Femenina',7)
 ,('ES','calcio','es_rfef','tercera_federacion_femenina','Tercera Federación Femenina',8)
 ,('ES','calcio','es_rfef','giovanili','Giovanili',9)
 ,('ES','futsal','es_rfef','segunda_division_b_de_futbol_sala','Segunda División B de Fútbol Sala',1)
 ,('ES','futsal','es_rfef','tercera_division_de_futbol_sala','Tercera División de Fútbol Sala',2)
 ,('ES','futsal','es_rfef','liga_regional_de_futbol_sala','Liga Regional de Fútbol Sala',3)
 ,('ES','futsal','es_rfef','liga_provincial_de_futbol_sala','Liga Provincial de Fútbol Sala',4)
 ,('ES','futsal','es_rfef','segunda_division_femenina_de_futbol_sala','Segunda División Femenina de Fútbol Sala',5)
 ,('ES','pallacanestro','es_feb','tercera_feb','Tercera FEB',1)
 ,('ES','pallacanestro','es_feb','liga_femenina_2_lf2','Liga Femenina 2 (LF2)',2)
 ,('ES','pallacanestro','es_feb','primera_nacional','Primera Nacional',3)
 ,('ES','pallacanestro','es_feb','liga_autonomica','Liga Autonómica',4)
 ,('ES','pallacanestro','es_feb','senior_provincial','Senior Provincial',5)
 ,('ES','pallacanestro','es_feb','senior_local','Senior Local',6)
 ,('ES','pallamano','es_rfebm','primera_nacional_masculina','Primera Nacional Masculina',1)
 ,('ES','pallamano','es_rfebm','segunda_nacional_masculina','Segunda Nacional Masculina',2)
 ,('ES','pallamano','es_rfebm','division_de_honor_plata_femenina','División de Honor Plata Femenina',3)
 ,('ES','pallamano','es_rfebm','primera_territorial','Primera Territorial',4)
 ,('ES','pallamano','es_rfebm','segunda_territorial','Segunda Territorial',5)
 ,('ES','rugby','es_rfer','division_de_honor_b_masculina','División de Honor B Masculina',1)
 ,('ES','rugby','es_rfer','giovanili','Giovanili',2)
 ,('ES','rugby','es_rfer','division_de_honor_femenina','División de Honor Femenina',3)
 ,('ES','rugby','es_rfer','division_de_honor_b_femenina','División de Honor B Femenina',4)
 ,('ES','rugby','es_rfer','primera_categoria_regional','Primera Categoría Regional',5)
 ,('ES','rugby','es_rfer','segunda_categoria_regional','Segunda Categoría Regional',6)
 ,('ES','pallavolo','es_rfevb','superliga_masculina_2','Superliga Masculina 2',1)
 ,('ES','pallavolo','es_rfevb','primera_division_masculina','Primera División Masculina',2)
 ,('ES','pallavolo','es_rfevb','superliga_2_femenina','Superliga 2 Femenina',3)
 ,('ES','pallavolo','es_rfevb','primera_division_femenina','Primera División Femenina',4)
 ,('ES','pallavolo','es_rfevb','primera_autonomica','Primera Autonómica',5)
 ,('ES','pallavolo','es_rfevb','segunda_autonomica','Segunda Autonómica',6)
 ,('ES','hockey_su_ghiaccio','es_rfedh','liga_nacional_de_hockey_hielo_lnhh','Liga Nacional de Hockey Hielo (LNHH)',1)
 ,('ES','hockey_su_ghiaccio','es_rfedh','liga_senior_femenina','Liga Senior Femenina',2)
 ,('ES','hockey_su_ghiaccio','es_rfedh','giovanili','Giovanili',3)
 ,('ES','pallanuoto','es_rfen','primera_division_masculina','Primera División Masculina',1)
 ,('ES','pallanuoto','es_rfen','segunda_division_masculina','Segunda División Masculina',2)
 ,('ES','pallanuoto','es_rfen','primera_division_femenina','Primera División Femenina',3)
 ,('ES','pallanuoto','es_rfen','liga_autonomica','Liga Autonómica',4)
 ,('ES','pallanuoto','es_rfen','liga_provincial','Liga Provincial',5)
 ,('ES','hockey_su_prato','es_rfeh','division_de_honor_a_masculina','División de Honor A Masculina',1)
 ,('ES','hockey_su_prato','es_rfeh','division_de_honor_b_masculina','División de Honor B Masculina',2)
 ,('ES','hockey_su_prato','es_rfeh','primera_division_masculina','Primera División Masculina',3)
 ,('ES','hockey_su_prato','es_rfeh','division_de_honor_femenina','División de Honor Femenina',4)
 ,('ES','hockey_su_prato','es_rfeh','division_de_honor_b_femenina','División de Honor B Femenina',5)
 ,('ES','baseball','es_rfebs','division_de_honor_oro_beisbol','División de Honor Oro (Béisbol)',1)
 ,('ES','baseball','es_rfebs','division_de_honor_plata_beisbol','División de Honor Plata (Béisbol)',2)
 ,('ES','baseball','es_rfebs','liga_regional','Liga Regional',3)
 ,('ES','softball','es_rfebs','division_de_honor_oro_femenina_sofbol','División de Honor Oro Femenina (Sófbol)',1)
 ,('ES','softball','es_rfebs','liga_regional','Liga Regional',2)
 ,('ES','football_americano','es_fefa','lnfa','LNFA',1)
 ,('ES','football_americano','es_fefa','lnfa_2','LNFA 2',2)
 ,('ES','football_americano','es_fefa','lnfa_femenina','LNFA Femenina',3)
 ,('ES','football_americano','es_fefa','liga_regional_serie_c_territoriales','Liga Regional (Serie C / Territoriales)',4)
 ,('ES','lacrosse','es_ael','liga_espanola_de_lacrosse_lel','Liga Española de Lacrosse (LEL)',1)
 ,('CH','calcio','ch_asf_sfv','1_liga_classic','1. Liga Classic',1)
 ,('CH','calcio','ch_asf_sfv','2_liga_interregional','2. Liga interregional',2)
 ,('CH','calcio','ch_asf_sfv','2_liga','2. Liga',3)
 ,('CH','calcio','ch_asf_sfv','3_liga','3. Liga',4)
 ,('CH','calcio','ch_asf_sfv','4_liga','4. Liga',5)
 ,('CH','calcio','ch_asf_sfv','5_liga','5. Liga',6)
 ,('CH','calcio','ch_asf_sfv','1_liga_frauen','1. Liga Frauen',7)
 ,('CH','calcio','ch_asf_sfv','giovanili','Giovanili',8)
 ,('CH','hockey_su_ghiaccio','ch_sihf','myhockey_league','MyHockey League',1)
 ,('CH','hockey_su_ghiaccio','ch_sihf','1_liga','1. Liga',2)
 ,('CH','hockey_su_ghiaccio','ch_sihf','2_liga','2. Liga',3)
 ,('CH','hockey_su_ghiaccio','ch_sihf','3_liga','3. Liga',4)
 ,('CH','hockey_su_ghiaccio','ch_sihf','4_liga','4. Liga',5)
 ,('CH','hockey_su_ghiaccio','ch_sihf','swhl_b','SWHL B',6)
 ,('CH','hockey_su_ghiaccio','ch_sihf','swhl_c','SWHL C',7)
 ,('CH','hockey_su_ghiaccio','ch_sihf','swhl_d','SWHL D',8)
 ,('CH','floorball','ch_swiss_unihockey','nlb_herren','NLB Herren',1)
 ,('CH','floorball','ch_swiss_unihockey','1_liga_grossfeld','1. Liga Grossfeld',2)
 ,('CH','floorball','ch_swiss_unihockey','2_liga','2. Liga',3)
 ,('CH','floorball','ch_swiss_unihockey','3_liga','3. Liga',4)
 ,('CH','floorball','ch_swiss_unihockey','4_liga','4. Liga',5)
 ,('CH','floorball','ch_swiss_unihockey','kleinfeld','Kleinfeld',6)
 ,('CH','pallacanestro','ch_swiss_basketball','nlb_men','NLB Men',1)
 ,('CH','pallacanestro','ch_swiss_basketball','nl1_men','NL1 Men',2)
 ,('CH','pallacanestro','ch_swiss_basketball','2ln','2LN',3)
 ,('CH','pallacanestro','ch_swiss_basketball','3ln','3LN',4)
 ,('CH','pallacanestro','ch_swiss_basketball','regional','Regional',5)
 ,('CH','pallacanestro','ch_swiss_basketball','nlb_women','NLB Women',6)
 ,('CH','pallamano','ch_shv_fsh','nlb_herren','NLB Herren',1)
 ,('CH','pallamano','ch_shv_fsh','1_liga','1. Liga',2)
 ,('CH','pallamano','ch_shv_fsh','2_liga','2. Liga',3)
 ,('CH','pallamano','ch_shv_fsh','3_liga','3. Liga',4)
 ,('CH','pallamano','ch_shv_fsh','4_liga','4. Liga',5)
 ,('CH','pallamano','ch_shv_fsh','spl2','SPL2',6)
 ,('CH','pallavolo','ch_swiss_volley','nlb','NLB',1)
 ,('CH','pallavolo','ch_swiss_volley','1_liga','1. Liga',2)
 ,('CH','pallavolo','ch_swiss_volley','2_liga','2. Liga',3)
 ,('CH','pallavolo','ch_swiss_volley','3_liga','3. Liga',4)
 ,('CH','pallavolo','ch_swiss_volley','4_liga','4. Liga',5)
 ,('CH','pallavolo','ch_swiss_volley','5_liga','5. Liga',6)
 ,('CH','sci','ch_swiss_ski','kantonalcup','Kantonalcup',1)
 ,('CH','sci','ch_swiss_ski','regionalrennen','Regionalrennen',2)
 ,('CH','sci','ch_swiss_ski','giovanili','Giovanili',3)
 ,('CH','biathlon','ch_swiss_ski','giovanili','Giovanili',1)
 ,('CH','tennis','ch_swiss_tennis','nlb_interclub','NLB Interclub',1)
 ,('CH','tennis','ch_swiss_tennis','1_liga_interclub','1. Liga Interclub',2)
 ,('CH','tennis','ch_swiss_tennis','2_liga_interclub','2. Liga Interclub',3)
 ,('CH','tennis','ch_swiss_tennis','3_liga_interclub','3. Liga Interclub',4)
 ,('CH','rugby','ch_fsr','lna','LNA',1)
 ,('CH','rugby','ch_fsr','lnb','LNB',2)
 ,('CH','rugby','ch_fsr','lnc','LNC',3)
 ,('CH','rugby','ch_fsr','lnd','LND',4)
 ,('CH','futsal','ch_asf_sfv','swiss_futsal_premier_league','Swiss Futsal Premier League',1)
 ,('CH','futsal','ch_asf_sfv','swiss_futsal_second_league','Swiss Futsal Second League',2)
 ,('CH','futsal','ch_asf_sfv','ligue_regionale_futsal','Ligue Régionale Futsal',3)
 ,('CH','calcio_a_7','ch_sffs','firmensport_fussball_7er','Firmensport Fussball 7er',1)
 ,('SI','calcio','si_nzs','3_snl','3. SNL',1)
 ,('SI','calcio','si_nzs','regionalna_nogometna_liga','Regionalna nogometna liga',2)
 ,('SI','calcio','si_nzs','enotna_primorska_liga','Enotna primorska liga',3)
 ,('SI','calcio','si_nzs','1_mnz_liga','1. MNZ Liga',4)
 ,('SI','calcio','si_nzs','2_mnz_liga','2. MNZ Liga',5)
 ,('SI','calcio','si_nzs','giovanili','Giovanili',6)
 ,('SI','calcio_a_7','si_smz','liga_ena','Liga ENA',1)
 ,('SI','futsal','si_nzs','2_sfl','2. SFL',1)
 ,('SI','futsal','si_nzs','obmocne_futsal_lige','Območne futsal lige',2)
 ,('SI','pallacanestro','si_kzs','3_skl','3. SKL',1)
 ,('SI','pallacanestro','si_kzs','4_skl','4. SKL',2)
 ,('SI','pallacanestro','si_organizzatori_locali','parkl','PARKL',1)
 ,('SI','pallacanestro','si_organizzatori_locali','rekreacijske_lige','Rekreacijske lige',2)
 ,('SI','pallamano','si_rzs','2_srl','2. SRL',1)
 ,('SI','pallavolo','si_ozs','2_dol','2. DOL',1)
 ,('SI','pallavolo','si_ozs','3_dol','3. DOL',2)
 ,('SI','pallavolo','si_ozs','regijske_odbojkarske_lige','Regijske odbojkarske lige',3)
 ,('SI','hockey_su_ghiaccio','si_organizzatori_locali','liga_ehl','Liga EHL',1)
 ,('SI','hockey_su_ghiaccio','si_organizzatori_locali','mariborska_liga','Mariborska liga',2)
 ,('SI','pallanuoto','si_zvds','1_clanska_vaterpolska_liga','1. članska vaterpolska liga',1)
 ,('SI','pallanuoto','si_zvds','giovanili','Giovanili',2)
 ,('SI','hockey_su_prato','si_zhts','drzavno_prvenstvo_v_hokeju_na_travi','Državno prvenstvo v hokeju na travi',1)
 ,('SI','hockey_su_prato','si_zhts','dvoranski_hokej','Dvoranski hokej',2)
 ,('SI','baseball','si_zbss','slovenska_baseball_liga_sbl','Slovenska baseball liga (SBL)',1)
 ,('SI','softball','si_zbss','slovenska_softball_liga','Slovenska softball liga',1)
 ,('SI','football_americano','si_zans','drzavno_prvenstvo_v_ameriskem_nogometu','Državno prvenstvo v ameriškem nogometu',1)
 ,('SI','football_americano','si_zans','slovenska_flag_football_liga_sffl','Slovenska Flag Football Liga (SFFL)',2)
 ,('SI','rugby','si_rzs_rugby','drzavno_prvenstvo_v_ragbiju','Državno prvenstvo v ragbiju',1)
 ,('SI','lacrosse','si_slovenia_lacrosse','slovenska_lacrosse_liga','Slovenska lacrosse liga',1)
 ,('SI','lacrosse','si_slovenia_lacrosse','torneji','Torneji',2)
 ,('PL','calcio','pl_pzpn','3_liga','3. Liga',1)
 ,('PL','calcio','pl_pzpn','4_liga','4. Liga',2)
 ,('PL','calcio','pl_pzpn','klasa_okregowa_okregowka','Klasa Okręgowa (Okręgówka)',3)
 ,('PL','calcio','pl_pzpn','klasa_a','Klasa A',4)
 ,('PL','calcio','pl_pzpn','klasa_b','Klasa B',5)
 ,('PL','calcio','pl_pzpn','klasa_c','Klasa C',6)
 ,('PL','calcio','pl_pzpn','1_liga_kobiet','1. Liga Kobiet',7)
 ,('PL','calcio','pl_pzpn','2_liga_kobiet','2. Liga Kobiet',8)
 ,('PL','calcio','pl_pzpn','3_liga_kobiet','3. Liga Kobiet',9)
 ,('PL','calcio','pl_pzpn','giovanili','Giovanili',10)
 ,('PL','calcio_a_6','pl_playarena_socca_poland','liga_playarena','Liga Playarena',1)
 ,('PL','calcio_a_6','pl_playarena_socca_poland','mistrzostwa_polski_socca','Mistrzostwa Polski Socca',2)
 ,('PL','futsal','pl_pzpn','1_liga_futsalu','1. Liga Futsalu',1)
 ,('PL','futsal','pl_pzpn','2_liga_futsalu','2. Liga Futsalu',2)
 ,('PL','futsal','pl_pzpn','ligi_srodowiskowe','Ligi Środowiskowe',3)
 ,('PL','futsal','pl_pzpn','ekstraliga_kobiety_futsal','Ekstraliga Kobiety Futsal',4)
 ,('PL','pallacanestro','pl_pzkosz','2_liga_mezczyzn','2. Liga Mężczyzn',1)
 ,('PL','pallacanestro','pl_pzkosz','3_liga_mezczyzn','3. Liga Mężczyzn',2)
 ,('PL','pallacanestro','pl_pzkosz','ligi_regionalne','Ligi Regionalne',3)
 ,('PL','pallacanestro','pl_pzkosz','1_liga_kobiet','1. Liga Kobiet',4)
 ,('PL','pallamano','pl_zprp','i_liga_mezczyzn','I Liga Mężczyzn',1)
 ,('PL','pallamano','pl_zprp','ii_liga_mezczyzn','II Liga Mężczyzn',2)
 ,('PL','pallamano','pl_zprp','iii_liga_mezczyzn','III Liga Mężczyzn',3)
 ,('PL','pallamano','pl_zprp','liga_centralna_kobiet','Liga Centralna Kobiet',4)
 ,('PL','pallamano','pl_zprp','i_liga_kobiet','I Liga Kobiet',5)
 ,('PL','pallavolo','pl_pzps','2_liga_mezczyzn','2. Liga Mężczyzn',1)
 ,('PL','pallavolo','pl_pzps','3_liga_mezczyzn','3. Liga Mężczyzn',2)
 ,('PL','pallavolo','pl_pzps','4_liga_mezczyzn','4. Liga Mężczyzn',3)
 ,('PL','hockey_su_ghiaccio','pl_pzhl','1_liga_mhl','1. Liga (MHL)',1)
 ,('PL','hockey_su_ghiaccio','pl_pzhl','2_liga','2. Liga',2)
 ,('PL','hockey_su_ghiaccio','pl_pzhl','liga_hokeja_kobiet','Liga Hokeja Kobiet',3)
 ,('PL','pallanuoto','pl_pzp','ekstraklasa_piki_wodnej','Ekstraklasa Piłki Wodnej',1)
 ,('PL','pallanuoto','pl_pzp','1_liga_piki_wodnej','1. Liga Piłki Wodnej',2)
 ,('PL','hockey_su_prato','pl_pzht','superliga_hokeja_na_trawie','Superliga Hokeja na Trawie',1)
 ,('PL','hockey_su_prato','pl_pzht','1_liga_hokeja_na_trawie','1. Liga Hokeja na Trawie',2)
 ,('PL','hockey_su_prato','pl_pzht','halowy_hokej_na_trawie','Halowy Hokej na Trawie',3)
 ,('PL','baseball','pl_pzbis','ekstraliga_baseballowa','Ekstraliga Baseballowa',1)
 ,('PL','baseball','pl_pzbis','1_liga_baseballowa','1. Liga Baseballowa',2)
 ,('PL','softball','pl_pzbis','ekstraliga_softballu_kobiet','Ekstraliga Softballu Kobiet',1)
 ,('PL','football_americano','pl_zfap','pfl_1','PFL 1',1)
 ,('PL','football_americano','pl_zfap','pfl_2','PFL 2',2)
 ,('PL','football_americano','pl_zfap','pfl_9','PFL 9',3)
 ,('PL','football_americano','pl_zfap','flag_football','Flag Football',4)
 ,('PL','football_americano','pl_zfap','giovanili','Giovanili',5)
 ,('PL','rugby','pl_pzr','ekstraliga_rugby','Ekstraliga Rugby',1)
 ,('PL','rugby','pl_pzr','1_liga_rugby','1. Liga Rugby',2)
 ,('PL','rugby','pl_pzr','2_liga_rugby','2. Liga Rugby',3)
 ,('PL','rugby','pl_pzr','mistrzostwa_polski_rugby_7','Mistrzostwa Polski Rugby 7',4)
 ,('PL','lacrosse','pl_pfl','polska_liga_lacrosse_pll','Polska Liga Lacrosse (PLL)',1)
), scope as (
 select seed.*,o.id organization_id,c.id country_id,s.id sport_id,d.id discipline_id,v.id variant_id
 from seed join public.countries c on c.iso2=seed.iso2
 join public.sports_organizations o on o.code=seed.org_code
 join public.sports s on s.code=case
  when sport_key in ('calcio','calcio_a_6','calcio_a_7','calcio_a_8','futsal') then 'football'
  when sport_key='pallavolo' then 'volleyball' when sport_key='pallacanestro' then 'basketball'
  when sport_key='pallanuoto' then 'water_polo' when sport_key='pallamano' then 'handball'
  when sport_key='hockey_su_prato' then 'field_hockey' when sport_key='hockey_su_ghiaccio' then 'ice_hockey'
  when sport_key='football_americano' then 'american_football' when sport_key='sci' then 'skiing' else sport_key end
 left join public.sport_disciplines d on d.sport_id=s.id and d.code=case when sport_key like 'calcio%' then 'association_football' when sport_key='futsal' then 'futsal' end
 left join public.sport_variants v on v.discipline_id=d.id and v.code=case sport_key when 'calcio' then 'eleven_a_side' when 'calcio_a_6' then 'six_a_side' when 'calcio_a_7' then 'seven_a_side' when 'calcio_a_8' then 'eight_a_side' end
)
insert into public.sports_organization_categories(id,organization_id,country_id,sport_id,discipline_id,variant_id,code,canonical_name,provider,source_record_id,source_version,source_metadata,is_active,display_order)
select md5('five-country-cat:'||iso2||':'||sport_key||':'||org_code||':'||code)::uuid,organization_id,country_id,sport_id,discipline_id,variant_id,org_code||'_'||sport_key||'_'||code,name,'clubandplayer_authorized_catalog',iso2||':'||sport_key||':'||org_code||':category:'||code,'2026-09-15.five-country','{"evidence":"section_5_closed_list"}',true,ord from scope
on conflict(provider,source_record_id) do update set organization_id=excluded.organization_id,country_id=excluded.country_id,sport_id=excluded.sport_id,discipline_id=excluded.discipline_id,variant_id=excluded.variant_id,code=excluded.code,canonical_name=excluded.canonical_name,source_version=excluded.source_version,source_metadata=excluded.source_metadata,is_active=true,display_order=excluded.display_order,updated_at=now();

-- Enforce country and the complete matrix in the database while permitting
-- deactivation/primary maintenance of legacy rows whose category was retired.
create or replace function public.validate_club_sport_registration() returns trigger
language plpgsql set search_path=public as $$
begin
 if not exists(select 1 from public.profiles p where p.id=new.club_profile_id and p.account_type='club') then
   raise exception 'registration_requires_club_profile';
 end if;
 if new.is_active and (tg_op='INSERT' or not coalesce(old.is_active,false)
   or new.sport_id is distinct from old.sport_id
   or new.sport_discipline_id is distinct from old.sport_discipline_id
   or new.sport_variant_id is distinct from old.sport_variant_id
   or new.sports_organization_id is distinct from old.sports_organization_id
   or new.sports_organization_category_id is distinct from old.sports_organization_category_id) then
   if not exists(
     select 1 from public.sports_organization_categories c
     join public.sports_organizations o on o.id=c.organization_id
     join public.profiles p on p.id=new.club_profile_id
     left join public.profile_preferences pp on pp.profile_id=p.id
     left join public.legacy_country_mappings lcm on lcm.normalized_source_value=lower(btrim(p.country)) and lcm.is_active
     where c.id=new.sports_organization_category_id and c.organization_id=new.sports_organization_id
       and c.country_id=coalesce(pp.residence_country_id,lcm.country_id) and c.sport_id=new.sport_id
       and c.discipline_id is not distinct from new.sport_discipline_id
       and c.variant_id is not distinct from new.sport_variant_id and c.is_active and o.is_active
   ) then raise exception 'incompatible_club_sport_registration'; end if;
 end if;
 if new.is_primary and new.is_active then
   update public.club_sport_registrations set is_primary=false,updated_at=now()
   where club_profile_id=new.club_profile_id and id<>new.id and is_primary;
 end if;
 new.updated_at=now(); return new;
end $$;

commit;
