import assert from 'node:assert/strict'; import { readFileSync } from 'node:fs'; import test from 'node:test';
import { createCompetitiveOptionsGetHandler } from '../../app/api/taxonomy/competitive-options/route';
import type { MaterializedCompetitiveOptionQuery, MaterializedCompetitiveOptionResult } from '../../lib/taxonomy/materializedCompetitiveOptions.server';
const c='11111111-1111-4111-8111-111111111111', s='22222222-2222-4222-8222-222222222222', o='33333333-3333-4333-8333-333333333333', d='44444444-4444-4444-8444-444444444444', v='55555555-5555-4555-8555-555555555555';
class Reader { calls: MaterializedCompetitiveOptionQuery[]=[]; result: MaterializedCompetitiveOptionResult={status:'ok',organizationId:o,options:[]}; error: Error|null=null; async list(q:MaterializedCompetitiveOptionQuery){this.calls.push(q);if(this.error)throw this.error;return this.result;} }
const setup=()=>{const reader=new Reader();return{reader,handler:createCompetitiveOptionsGetHandler(async()=>reader)}}; const request=(q='')=>new Request(`http://localhost/api/taxonomy/competitive-options${q}`); const base=`?countryId=${c}&sportId=${s}&organizationId=${o}`;
test('requires all parents and rejects empty optional parameters',async()=>{for(const q of ['',`?countryId=${c}&sportId=${s}`,`${base}&limit=`])assert.equal((await setup().handler(request(q))).status,400)});
test('forwards boundary limits and a non-numeric limit fails closed',async()=>{for(const limit of ['1','200']){const x=setup();await x.handler(request(`${base}&limit=${limit}`));assert.equal(x.reader.calls[0]?.limit,Number(limit))}const x=setup();x.reader.result={status:'invalid_query',options:[]};assert.equal((await x.handler(request(`${base}&limit=many`))).status,400)});
test('forwards the exact contract without kinds and returns empty options no-store',async()=>{const x=setup();const r=await x.handler(request(`${base}&disciplineId=${d}&variantId=${v}&asOf=2026-09-13&limit=200`));assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'no-store');assert.deepEqual(x.reader.calls,[{countryId:c,sportId:s,organizationId:o,disciplineId:d,variantId:v,asOf:'2026-09-13',limit:200}]);assert.deepEqual(await r.json(),{ok:true,organizationId:o,options:[]})});
test('maps every failure status and sanitizes datasource errors',async()=>{for(const [status,code] of [['invalid_query',400],['invalid_scope',400],['unsupported_country',404],['inactive_sport',404],['unavailable_organization',404],['overflow',409]] as const){const x=setup();x.reader.result={status,options:[]};const r=await x.handler(request(base));assert.equal(r.status,code);assert.equal(r.headers.get('cache-control'),'no-store')}const x=setup();x.reader.error=new Error('postgres secret');const r=await x.handler(request(base));assert.equal(r.status,500);assert.equal((await r.text()).includes('postgres secret'),false)});
test('GET-only route uses anon/session client, no-store and excludes unauthorized families and mutation surfaces',()=>{const route=readFileSync(new URL('../../app/api/taxonomy/competitive-options/route.ts',import.meta.url),'utf8');const repo=readFileSync(new URL('../../lib/taxonomy/materializedCompetitiveOptions.server.ts',import.meta.url),'utf8');assert.match(route,/export const GET =/);assert.match(route,/getSupabaseServerClient\(\)/);assert.match(route,/force-no-store/);assert.doesNotMatch(route,/['"]kinds['"]/);assert.doesNotMatch(route+repo,/service.?role|SUPABASE_SERVICE|\.insert\(|\.update\(|\.upsert\(|\.delete\(|\.rpc\(/i);assert.doesNotMatch(route,/export (?:async function|const) (?:POST|PUT|PATCH|DELETE)/);for(const forbidden of ["from('age_classes')","from('competition_groups')","kind: 'age_category'","kind: 'territorial_group'","kind: 'league'","kind: 'cup'","kind: 'tournament'","kind: 'gender_category'","kind: 'youth_umbrella'"])assert.equal(repo.includes(forbidden),false,forbidden)});
